### ISSUE TITLE
即時完了するシーケンスでReadOnlyReactivePropertySlim

### ISSUE THREAD

**Issue by toras9000** [runceel/ReactiveProperty#105]
即時完了する(Subscribeが同期的に完了する)シーケンスを基にReadOnlyReactivePropertySlimを作ろうとした場合、NullReferenceExceptionが発生します。
例えば、簡単に再現する例としては以下のような場合になります。

`Observable.Return(1).ToReadOnlyReactivePropertySlim();`

見た限りでは、ReadOnlyReactivePropertySlimのコンストラクタ内でシーケンスをSubscribe()した際にOnCompleted()→Dispose()まで処理されて、未初期化フィールドsourceSubscriptionのDispose()呼び出しで発生するように思われます。

そういったシーケンスの場合はReactivePropertyにする意味があまりなくてそもそも対象としていないのかもしれませんが、一応報告させていただきます。

**Comment by runceel** [comment]
### English short summary for not Japanese users.

NullPointerException occurr when runing following code:

```cs
Observable.Return(1).ToReadOnlyReactivePropertySlim();
```

#### Cause of the error

When create ReadOnlyReactivePropertySlim from Observable instance that raise a complete event immediately, ReadOnlyReactivePropertySlim class access to non initialized class field at Dispose method, then the error is occurred.

**Comment by runceel** [comment]
ありがとうございます。修正してリリースしました。

https://github.com/runceel/ReactiveProperty/releases/tag/v5.5.1

---
English

Thank you for sending feedback!
I fixed the issue, then I released a new version to NuGet.

https://github.com/runceel/ReactiveProperty/releases/tag/v5.5.1
