### ISSUE TITLE
I want "another ReactiveCollection" to call only CollectionChanged in the scheduler

### ISSUE THREAD

**Issue by punio** [runceel/ReactiveProperty#106]
The current ReactiveCollection is supposed to call each method of ObservableCollection in the scheduler.
In this case, each value of Collection will not be updated until it is executed by the scheduler.

```cs
var collection = new ReactiveCollection<int>();
Task.Run(() =>
{
	collection.AddOnScheduler(1);
	Console.WriteLine($"{collection.Count}");   // -> 0
	collection[0] = 2; // System.ArgumentOutOfRangeException
});
````

Immediately after calling the method (...OnScheduler), the contents of the collection are updated and only CollectionChanged will be called later via the scheduler.
It is nice to be able to use it like an ordinary collection with this implementation.

---
日本語

CollectionChangedだけをスケジューラーで呼び出すReactiveCollectionが欲しい

現在のReactiveCollectionはObservableCollectionの各メソッドをスケジューラーで呼び出すようになっていると思います。
この場合スケジューラーで実行されるまでCollectionの各値は更新されません。

メソッド(～OnScheduler)を呼び出した直後にコレクションの中身が更新されCollectionChangedだけが後からスケジューラー経由で飛ぶ、ような感じだと普通のコレクションと同じような使い方ができてうれしいです

**Comment by runceel** [comment]
Thank you for your feedback. And I'm so sorry to late replying your feedback.

I think the behavior happen some bugs.
I think the update timing and raise CollectionChanged event timing have to do same timing on same thread.
If not same timing, then event subscriber confuse.
For example:
You add an item, and then clear collection.
When event receiver received an added event, it might the collection already cleared.

===
Japanese

変更とイベントのタイミングが異なると、追加してクリアーしたときに追加イベントを処理するタイミングで既にコレクションがクリアーされてるといったことが起こると思うので何か変なことが起こると思います。
