### ISSUE TITLE
ReactiveProperty based on multiple properties

### ISSUE THREAD

**Issue by animha** [runceel/ReactiveProperty#112]
Hello,

I found your project and look very interesting to me. I'm trying to use it with Xamarin.Forms

My issue is a question rather than a issue.

In documentation you explain how to obtain "derivate properties" using .ToReactiveProperty.
I was wondering if it was possible to get a reactive property based on multiple observables.

For example:
I have 3 ReactiveProperties:

var name = new ReactiveProperty<string>();
var surname = new ReactiveProperty<string>();
var age = new ReactiveProperty<int>();

I want to obtain a ReactiveProperty (read-only is good) that tiggers if ANY of the three ReactiveProperty above change.

Is that possible?

Thank you and good job!

**Comment by WITCHeYyY** [comment]
You can use `Observable.Merge` as follows:

```
var name = new ReactiveProperty<string>();
var surname = new ReactiveProperty<string>();
var age = new ReactiveProperty<string>();

var mergedProperty = Observable.Merge(name, surname, age)
    .ToReadOnlyReactiveProperty();
```

**Comment by runceel** [comment]
@animha 
Thank you for commenting.

In this case, I think `Observable.CombineLatest` is better than `Observable.Merge`, because almost all cases, you will want to use value of each properties to create a new property.

### for example

```cs
using System;
using System.Reactive.Linq;
using Reactive.Bindings;

namespace RpEdu
{
    class Program
    {
        static void Main(string[] args)
        {
            var firstName = new ReactiveProperty<string>("Kazuki");
            var lastName = new ReactiveProperty<string>("Ota");
            var age = new ReactiveProperty<int>(38);

            var profile = Observable.CombineLatest(firstName, lastName, age, (f, l, a) => $"{f} {l}({a})")
                .ToReadOnlyReactiveProperty();

            Console.WriteLine(profile.Value); // Kazuki Ota(38)
            firstName.Value = "Taro";
            Console.WriteLine(profile.Value); // Taro Ota(38)
        }
    }
}
```

**Comment by runceel** [comment]
I close the issue because keep to clean the repository.
If you have a question related this, then feel free re-open this.

Thank you for using ReactiveProperty. ;)
