### ISSUE TITLE
ReactiveCommand.CanExecute should be more accessible

### ISSUE THREAD

**Issue by JohnBillington** [runceel/ReactiveProperty#12]
The three parts of this issue are:

1. It would be nice to be able to override the `CanExecute` method (right now it's not virtual).
2. It would be nice if there were constructors for `ReactiveCommand` that took a parameter of type `Action<object>`, which would provide the `CanExecute` functionality for that `ReactiveCommand`.
3. There should probably be corresponding constructors for `ReactiveCommand<T>` that take a parameter of type `Action<T>`.

The reason for needing the original functionality of `CanExecute` is that it takes an object parameter, and there is no way to have similar functionality when specifying the `IObservable<bool> canExecuteSource` parameter to the `ReactiveCommand` constructor.

The reason I would like this added to `ReactiveCommand` rather than just using something like `RelayCommand` from [MvvmLight](http://www.mvvmlight.net/) is that it's really, really nice to be able to subscribe to commands.

Note: I'm not sure if this issue should be two separate issues; I'll be happy to split it out if that's agreed to be a better choice.

**Comment by JohnBillington** [comment]
If it's agreed that this is a change this project wants, then I would be happy to contribute the code and do a pull request.

**Comment by runceel** [comment]
We think that ReactiveCommand should create from IObservable<bool>.
If you want to use like RelayCommand then you can use MvvmLight with ReactiveProperty.
ReactiveProperty don't conflict other MVVM library.

Thank you.
(My first language is Japanese. If I mislead your think then please response.)

**Comment by JohnBillington** [comment]
That's fine--I really appreciate your quick attention to this issue. Thank you!
