### ISSUE TITLE
Unable to use ReactiveProperty 6.0.3 with .NETCoreApp, Version 3.0 

### ISSUE THREAD

**Issue by TaviTruman** [runceel/ReactiveProperty#120]
I'm unable to update WPF apps that target .NET Core 3.0 when using VS 2019 (Production) or VS 2019 (Preview). Both VS 2019 environments current with the most recent updates and .NET Core 3.0 SDK is at Preview 7.

Severity	Code	Description	Project	File	Line	Suppression State
Error	NU1202	Package ReactiveProperty 6.0.3 is not compatible with netcoreapp3.0 (.NETCoreApp,Version=v3.0). Package ReactiveProperty 6.0.3 does not support any target frameworks.

**Comment by runceel** [comment]
@TaviTruman 
Thank you for your feedback.
I've checked it. However, I could use ReactiveProperty 6.0.3 on WPF on .NET Core 3.0.100-preview7-012821.
![image](https://user-images.githubusercontent.com/79868/62171812-37c46080-b36b-11e9-87a5-4c6be463415f.png)

I just created a new WPF app(.NET Core) project, and then I added ReactiveProperty to the project using NuGet Package Manager.

Could you tell me more details?
If you have been trying updating from .NET Framework, so, how about you remove ReactiveProperty reference from your project, and then re-install ReactiveProperty.

**Comment by TaviTruman** [comment]
Oh, that's right w.r.t. migrating from .NET Framework; I'll check that out now. I'll create a new WPF .NET Core App project from scratch and I'll enact the migration use-case too.

**Comment by TaviTruman** [comment]
I tried to create a new WPF App (.NET Core 3.0) and this is what I got:

It did not work.

![image](https://user-images.githubusercontent.com/5692812/62172504-4bc67e80-b2e7-11e9-840e-78455fba3631.png)

![image](https://user-images.githubusercontent.com/5692812/62172516-51bc5f80-b2e7-11e9-89be-aa497afb70f7.png)

![image](https://user-images.githubusercontent.com/5692812/62172531-5719aa00-b2e7-11e9-835f-60d0a17170dd.png)

![image](https://user-images.githubusercontent.com/5692812/62172536-5e40b800-b2e7-11e9-9991-6525857fb65c.png)

**Comment by TaviTruman** [comment]
Here is a summary of what I have installed:

![image](https://user-images.githubusercontent.com/5692812/62173196-ffc90900-b2e9-11e9-829f-bcda2ba6814c.png)

![image](https://user-images.githubusercontent.com/5692812/62173207-0c4d6180-b2ea-11e9-8fa4-b092ef8cc6b2.png)

![image](https://user-images.githubusercontent.com/5692812/62173228-225b2200-b2ea-11e9-85d2-17050b76c674.png)

![image](https://user-images.githubusercontent.com/5692812/62173237-2c7d2080-b2ea-11e9-9de3-59c30db67251.png)

![image](https://user-images.githubusercontent.com/5692812/62173316-6ea66200-b2ea-11e9-89ec-ee217021321d.png)

![image](https://user-images.githubusercontent.com/5692812/62173323-78c86080-b2ea-11e9-973e-bcc094b97b37.png)

So things have not changed on this machine in this environmnet.

**Comment by TaviTruman** [comment]
Okay, I got it to work but I am not able to get it to work vai VS 2019! I use the .NET CLI command from a VS Developer command windows: dotnet add package ReactiveProperty --version 6.0.3

![image](https://user-images.githubusercontent.com/5692812/62173921-baf2a180-b2ec-11e9-976d-a253444aaa6f.png)

So, I have sure what going on here; it does not look like there is something wrong with the ReactiveProperty package:

![image](https://user-images.githubusercontent.com/5692812/62173970-f2614e00-b2ec-11e9-8127-23b0ff95bf7b.png)

**Comment by runceel** [comment]
It is strange behavior....
I had re-added ReactiveProperty to WPF on .NET Core project, after deleting NuGet local cache folder(`c:\users\username\.nuget`).
It was succeed.
![image](https://user-images.githubusercontent.com/79868/62216649-1e132f80-b3e4-11e9-98b3-6afb5c7957a5.png)

Here is my Visual Studio version dialog. It is same as you.
![image](https://user-images.githubusercontent.com/79868/62216701-384d0d80-b3e4-11e9-8332-ae4958276875.png)

**Comment by TaviTruman** [comment]
This is very odd indeed; I have tried to reproduce this issue on two different machines and I'm getting two different sets of errors that don't make sense at all. I have opened a trouble ticket with the Visual Studio Team regarding the matter. I don't think anything is in error w.r.t the ReactiveProperty assembly. I'd like to keep this open for a bit longer as I might gain worthwhile insights.

**Comment by runceel** [comment]
I think you already know, but a following link is a nuspec file for ReactiveProperty.
https://github.com/runceel/ReactiveProperty/blob/master/BuildTools/ReactiveProperty.nuspec

If you found something mistake on the file, then please let me know.

**Comment by TaviTruman** [comment]
@neuecc I talked to the VS team and they recommended that I run repair on one of the machine where I encounted this strange behavior; the problem has been resolvbed. that running repair and the upgade from .NET Framework (4.7.2) WPF App to .NET Core 3.0 App, worked. I'm going to close this issue.

**Comment by runceel** [comment]
@TaviTruman I'm glad to hear fixing the issue.
BTW, my GitHub ID is runceel, not neuecc. :)

neuecc is original owner of ReactiveProperty.
He has been creating a lot of great and useful C# libraries.
If you feel interesting to ReactiveProperty, then I guess you check his repository, then you find more interesting libraries.

https://github.com/neuecc

**Comment by TaviTruman** [comment]
@runceel Yikes! I also use an open-source library by @neuecc too :-) So sorry for the mixup. Please, keep up the great work on ReactiveProperty!

**Comment by runceel** [comment]
Haha, thank you. :)
