### ISSUE TITLE
ReactiveProperty Documentation URL link is not working

### ISSUE THREAD

**Issue by TaviTruman** [runceel/ReactiveProperty#121]
![image](https://user-images.githubusercontent.com/5692812/62172757-46b5ff00-b2e8-11e9-842a-ac218e9de3f1.png)

**Comment by runceel** [comment]
Thank you for telling me.
I'll recover it at Today's night.

If you want to read the document, then please look a following link:
https://github.com/runceel/ReactiveProperty/tree/master/docs/docs

**Comment by runceel** [comment]
I checked it, I couldn't find cause of the issue.
Currently, https can't be displayed. http is available.

http://okazuki.jp/ReactiveProperty/

**Comment by runceel** [comment]
Fixed!

**Comment by TaviTruman** [comment]
@neuecc Thank you - the documentation combined with the source code and samples helps a great deal. ReactiveProperty is a very well designed and dependable; great API work.

**Comment by runceel** [comment]
Thank you. :)
I'm glad to use ReactiveProperty to you.
