### ISSUE TITLE
v6.0.3での.NET 4.6.1向けNuGet依存パッケージ

### ISSUE THREAD

**Issue by toras9000** [runceel/ReactiveProperty#125]
NuGetパッケージのスタンスにもよるかと思いますが、
ReactiveProperty v6.0.3 のNuGetパッケージにて .NET 4.6.1 向けのパッケージ依存関係に
System.ComponentModel.Annotations (>= 4.5.0) への依存も含める必要はないでしょうか？

ReactiveProperty v5.6.0 ではターゲットフレームワークが .NET 4.6.1 の時はおそらく .NETStandard 2.0 の依存関係から System.ComponentModel.Annotations パッケージへの依存が参照されていたかと思います。
ReactiveProperty v6.0.3 で .NET 4.6.1 向けの依存関係が明示的に定義されたため、バリデーションを使う場合はそこに含まれていない System.ComponentModel.Annotations の参照を別途手動で追加する必要が出ているかと思います。
その際、バージョン的にフレームワークのアセンブリではなくパッケージの参照を追加するべきかと思いますので、依存パッケージに含めるのが妥当なのではないかなと思っています。

**Comment by runceel** [comment]
あったほうが追加してすぐ使えるので便利ですね。
丁度、先ほど新しいパッケージ作ったので追加しました。

https://github.com/runceel/ReactiveProperty/releases/tag/v6.1.2
