### ISSUE TITLE
The type 'EventToReactiveProperty' from assembly 'ReactiveProperty.NET45' is built with an older version of the Blend SDK, and is not supported in a Windows Presentation Framework 4 project.

### ISSUE THREAD

**Issue by TaviTruman** [runceel/ReactiveProperty#13]
![2015-11-22_12-39-07](https://cloud.githubusercontent.com/assets/5692812/11326151/5f1ad37e-9116-11e5-9c35-64581573e18f.png)

**Comment by TaviTruman** [comment]
Guys this error disables visual editing in Blend 2015 and VS Ent 2015

![2015-11-22_12-45-09](https://cloud.githubusercontent.com/assets/5692812/11326177/2df4d88e-9117-11e5-8b80-97a0f5b76928.png)

**Comment by TaviTruman** [comment]
![2015-11-22_12-48-47](https://cloud.githubusercontent.com/assets/5692812/11326182/6b67a282-9117-11e5-98f0-adefed04aa24.png)

**Comment by runceel** [comment]
@TaviTruman I tryed to reproduce this issue. But I can't reproduce.


<img width="570" alt="default" src="https://cloud.githubusercontent.com/assets/79868/11328342/db14c5c4-91cb-11e5-8e34-b7fbf58ec0f3.PNG">

ReactiveProperty reference settings is here.

<img width="352" alt="2" src="https://cloud.githubusercontent.com/assets/79868/11328361/52798c08-91cc-11e5-9d68-8c970ba7b903.PNG">


We are adding ver 4.5.0.0 now.


Can you provide reproduce project?

**Comment by TaviTruman** [comment]
Yes, I will upload a sample project today.

**Comment by runceel** [comment]
@TaviTruman Thank you. I rebuild and released v2.2.8.1-pre package.
Please try this package.

**Comment by TaviTruman** [comment]
Absolutely, thank you!

**Comment by TaviTruman** [comment]
Okay guys the 2.2.8 release fixed this problem! I will upload a reference project for future testing.
