### ISSUE TITLE
Request: Remove use of Microsoft.Xaml.Behaviors.WPF so package can be used in AvaloniaUI

### ISSUE THREAD

**Issue by DooblyNoobly** [runceel/ReactiveProperty#133]
When using ReactiveProperty in an AvaloniaUI project you can only build for windows as `Microsoft.WindowsDesktop.App.WPF` is not available for osx and linux.

Error is thrown when building on these platforms:
`
There was no runtime pack for Microsoft.WindowsDesktop.App.WPF available for the specified RuntimeIdentifier 'osx-x64'
`

Request is for a cross platform alternative to be found for the use of Microsoft.WindowsDesktop.App.WPF

**Comment by runceel** [comment]
Thank you for your request.
That's correct. I'll re-desigin the NuGet package of ReactiveProperty for fix the issue.
Please use v6.1.3 until fixing it.

**Comment by DooblyNoobly** [comment]
Thanks v6.1.3 works

**Comment by runceel** [comment]
@DooblyNoobly 
I have released ReactiveProperty 7.0.0 pre-release version.
I think you can use it on macOS with AvaloniaUI.
