### ISSUE TITLE
Re-design NuGet packages

### ISSUE THREAD

**Issue by runceel** [runceel/ReactiveProperty#134]
I have been thinking that I try to separate the NuGet package to each platforms.
Because to support Avalonia UI(the related issue is #133)

Current idea is:
- ReactiveProperty(for all platforms)
- ReactiveProperty.Wpf(WPF on .NET and .NET Core)
- ReactiveProperty.XamarinAndroid
- ReactiveProperty.XamariniOS
- ReactiveProperty.UWP

Any other idea?

**Comment by vfrz** [comment]
It would allow to use it on blazor too, which could be awesome :)

**Comment by runceel** [comment]
@vfrz 
Thanks. I have been trying to convert projects to SDK style csproj file for easy to publish to nuget.org.
However, it is difficult. ;(
In my understanding, Xamarin and UWP don't support officially SDK style project.

**Comment by runceel** [comment]
I'll start it after .NET 5, because sdk style csproj on Xamarin will be supported on .NET 5.
https://devblogs.microsoft.com/dotnet/announcing-net-5-0-preview-1/

**Comment by ffgiraldez** [comment]
please support all Xamarin plarform, not just Android/iOS

**Comment by runceel** [comment]
@ffgiraldez
Is that the .net standard?
Could you tell me more details?

**Comment by ffgiraldez** [comment]
Xamarin has more flavours than just Android/iOS, others not so known are available, like Tizen, Mac or Linux via GTK#

**Comment by runceel** [comment]
I think ReactiveProperty can be used on Xamarin(includes Tize, Mac, Linux and others) via .NET Standard. Do I missunderstand?

**Comment by ffgiraldez** [comment]
if so, why need an specific `ReactiveProperty.XamarinAndroid` or `ReactiveProperty.UWP` if you will do that, please add also for the rest of the xamarin ecosystem and not just the popular ones, please

**Comment by runceel** [comment]
ReactiveProperty(.NET Std) includes the core features such as ReactiveProperty, ReactiveCommand, Notifier and extension methods.

ReactiveProperty for specific platforms are a few classes for each platforms.

Current package has all dll files that are ReactiveProperty.dll, ReactiveProperty.Android.dll and etc.
I expect .NET Core is WPF.
However, .NET Core has another UI framework Avalonia. A following issue was reported.
#133

So, I decided separating the package for each platforms.

Make sense?
