### ISSUE TITLE
ReactiveCollection issue

### ISSUE THREAD

**Issue by animha** [runceel/ReactiveProperty#135]
Hello,
I have this problem using ReactiveCollections (in Xamarin Forms).

_ReactiveCollection<PaymentType> PaymentTypes = new ReactiveCollection<PaymentType>();_
_PaymentTypes.AddRangeOnScheduler(lst);_ (lst contains some items.. lst.Count > 0)
_if (PaymentTypes.Count > 0)._..... this condition returns false, even if it should be true.

"AddRangeOnScheduler" has no await or similar to allow me to wait for the scheduling to be executed.. how can I do?

Thank you in advance for your help.

**Comment by runceel** [comment]
Hi @animha,

As you wrote, all of methods of `ReactiveCollection such as `AddRangeOnScheduler` is not able to wait.
It depends Scheduler you use(default scheduler is SynchronizedContextSchduler that is provided from ReactivePropertyScheduler class.)

If you would like to run logic on UI thread, then I suggest:

```cs
ObservableCollection<PaymentType> PaymentTypes = new ObservableCollection<PaymentType>();

ReactivePropertyScheduler.Default.Schedule(() =>
{
  foreach (var x in lst) { PaymentTypes.Add(x); }
  if (PaymentTypes.Count > 0) { ... }
});
```

or you can also use ReadOnlyReactiveCollection:

```cs
ObservableCollection<PaymentType> PaymentTypes = new ObservableCollection<PaymentType>();
ReadOnlyReactiveCollection<PaymentType> PaymentTypesForViewLayer = PaymentTypes.ToReadOnlyReactiveProperty();

foreach (var x in lst) { PaymentTypes.Add(x); }
if (PaymentTypes.Count > 0) { ... }
```

ReadOnlyReactiveProperty dispatch all collection changed events to UI thread automatically.

**Comment by animha** [comment]
Thank you, I opted for using standard ObservableCollection for my purpose.

**Comment by runceel** [comment]
`ReactiveCollection<T>` is for dispatch to the UI thread automatically, when using `***OnScheduler` methods. If you don't need that, then `ObservableCollection<T>` and other collection classes are fit. 😀
