### ISSUE TITLE
Proposal: extensions methods ObserveCountChanged and ObserveContentChanged

### ISSUE THREAD

**Issue by BADF00D** [runceel/ReactiveProperty#139]
Hi,
I needed an extension method that got notified when the count in an ObservableCollection changed. I use this for validation and thought, that might be a nice general purpose extension method that suits into [your existing once](https://okazuki.jp/ReactiveProperty/features/Extension-methods.html).

Since they are only depedent on INotifyCollectionChanged and ICollection, they work for the build-in ObservableCollection as well als the reactive once.

## ObserveCountChanged
```csharp

public static IObservable<int> ObserveCountChanged<T>(this T source)
	where T : INotifyCollectionChanged, ICollection
{
	return source.CollectionChangedAsObservable()
		.Where(args =>
			args.Action == NotifyCollectionChangedAction.Add ||
			args.Action == NotifyCollectionChangedAction.Remove ||
			args.Action == NotifyCollectionChangedAction.Reset)
		.Select(_ => source.Count)
		.Publish()
		.RefCount();
}
```

## ObserveContentChanged
```csharp
public static IObservable<Unit> ObserveContentChanged<T>(this T source)
	where T : INotifyCollectionChanged, ICollection
{
	return source.CollectionChangedAsObservable()
		.Where(args =>
			args.Action == NotifyCollectionChangedAction.Add ||
			args.Action == NotifyCollectionChangedAction.Remove ||
			args.Action == NotifyCollectionChangedAction.Reset ||
			args.Action == NotifyCollectionChangedAction.Replace
		)
		.Select(_ => Unit.Default);
}
```

**Comment by runceel** [comment]
Hi @BADF00D ,

Thank you for your feedback.
Those looks useful. I have questions to clear my understanding.

## ObserveCountChanged

For ObservableCollection case, I think you can use `ObserveProperty` like below:

```cs
using System;
using System.Collections.ObjectModel;
using Reactive.Bindings.Extensions;

namespace ObsColl
{
    class Program
    {
        static void Main(string[] args)
        {
            var c = new ObservableCollection<int>();
            c.ObserveProperty(x => x.Count).Subscribe(x => Console.WriteLine(x));

            c.Add(10);
            c.Add(10);
            c.Add(10);
            c.Add(10);
        }
    }
}
```

Output:
```
0
1
2
3
4
```

I know that all collections  such as `Reactive.Bindings.Helpers.IFilteredReadOnlyObservableCollection` are not implemented the feature.
I have to implement that to `Reactive.Bindings.Helpers.IFilteredReadOnlyObservableCollection`. 😅

### ObserveContentChanged

I think `ICollection` doesn't need at `where`. Correct?

**Comment by runceel** [comment]
I don't think the extension methods are useful.
ObserveCountChanged is substitutable by ObserveProperty. ObserveContentChanged is same as `x.CollectionChangedAsObservable().Where(x => x.Action != NotifyCollectionChangedAction.Move)`. It is short enough for writing.

And I was not able to image the use case.
