### ISSUE TITLE
XDG0062	Could not load file or assembly 'ReactiveProperty.NETCore, Version=6.2.0.0, Culture=neutral, PublicKeyToken=null'. The system cannot find the file specified.

### ISSUE THREAD

**Issue by TaviTruman** [runceel/ReactiveProperty#159]
I upgraded my WPF .NETCoreApp3.1 to the latest version of ReactiveProperty and now I'm getting this error:

![image](https://user-images.githubusercontent.com/5692812/82015587-ef450d80-9633-11ea-9f93-aaab5102cc3b.png)

on this XAML:

**
![image](https://user-images.githubusercontent.com/5692812/82015602-f835df00-9633-11ea-8612-b67423a10156.png)
**
![image](https://user-images.githubusercontent.com/5692812/82015699-40ed9800-9634-11ea-8e4b-b48f2377b1f9.png)

**Comment by runceel** [comment]
Thank you for the report.
Sorry, I didn't write the breaking change to the release note.

You have to change xmlns for EventToReactiveCommand/EventToReactiveProperty.

Before: assembly=ReactiveProperty.NetCore
After: assembly=ReactiveProperty.WPF

**Comment by runceel** [comment]
I have updated the release note.

https://github.com/runceel/ReactiveProperty/releases/tag/v7.0.0

**Comment by TaviTruman** [comment]
@runceel Thanks 😊. I took a look at the sample in the repository last night after I wrote the post and figured there must have been a namespace change. It works.
