### ISSUE TITLE
ReadOnlyReactiveProperty not raising latest value on subscribe

### ISSUE THREAD

**Issue by MattRames** [runceel/ReactiveProperty#163]
Subscribing to a ReadOnlyReactiveProperty built off a completed observable no longer raises the latest value on subscribe, even when setting the mode to RaiseLatestValueOnSubscribe. Was this intentional? 

Ex. 
```
IReadOnlyReactiveProperty<string> test1 = Observable.Return("1")
                                            .ToReadOnlyReactiveProperty();
test1.Subscribe(i => Debug.WriteLine("Hit test1 subscribe")); // This will not output

IReadOnlyReactiveProperty<string> test2 = new ReactiveProperty<string>("2");
test2.Subscribe(i => Debug.WriteLine("Hit test2 subscribe")); // This will output
```

Package version v7.1.0

**Comment by runceel** [comment]
@MattRames 
Thank you for reporting.
Yes, this is intentional behavior. Because the source IObservable is already completed.
You can use OnCompleted callback instead of OnNext in this case.

It is a notable breaking change from v6. But I forgot writing that to the release note.
I'll update it.

**Comment by runceel** [comment]
Is the issue serious for you?
If so, I'll add an option that works the same as v6.

**Comment by MattRames** [comment]
Thanks for the quick response. It's not a serious issue, I can work around it fairly easily.
