### ISSUE TITLE
Strong Name Signing

### ISSUE THREAD

**Issue by voneinem** [runceel/ReactiveProperty#17]
Please sign the assemblies with a strong name key.

**Comment by xin9le** [comment]
Thank you for your proposal :)

First of all, why do you want strong name signed assembly?
Do you plan to use our library as shared dll?

**Comment by voneinem** [comment]
We sign our executables with a strong name key.
All dlls we use have to be strong named as well.

**Comment by BADF00D** [comment]
You can fork the repository and sign it yourself. If you are afraid of the repeating work, simply use a build server. It can simply fetch new updated from github, create a signed nuget packet and it can publish it to you private nuget server (e.g. klondike).
