### ISSUE TITLE
ToReadOnlyReactiveCollectionすると発行されるNotifyCollectionChangedActionが変わる

### ISSUE THREAD

**Issue by ryo1988** [runceel/ReactiveProperty#177]
ObservableCollectionをToReadOnlyReactiveCollectionすると、
ObservableCollection.Moveした際に、ReadOnlyReactiveCollectionからNotifyCollectionChangedAction.RemoveとNotifyCollectionChangedAction.Addが発行されるのは何か制約などがあってこうなっているのでしょうか？
できれば、NotifyCollectionChangedAction.Moveを発行する挙動だとありがたいです。

**Comment by runceel** [comment]
ありがとうございます。
特に意図していないため修正したいと思います。

**Comment by runceel** [comment]
修正して 7.2.1 としてリリースしました。

https://www.nuget.org/packages/ReactiveProperty/7.2.1

**Comment by ryo1988** [comment]
素早いご対応ありがとうございます。
