### ISSUE TITLE
Idea for another way of creating reactive stuff

### ISSUE THREAD

**Issue by BADF00D** [runceel/ReactiveProperty#18]
I try to test everything and so I a little bit annoyed of the way reactive properties are created. More then a few times I wrote test that failed, because I simply forgot to include the correct IScheduler.

So I developed something I called IReactiveCretor. It can used in the following way:

````CSharp
    public class UserViewModel{
        public ReactiveProperty<bool> IsActive{get;}
        public ReactiveProperty<string> FamilyName {get;}
        public ReactiveProperty<string> Name {get;}
        public ReactiveProperty<DateTimeOffset> Age {get;}
        public ReactiveCommand DeleteUser {get; }
        
        ///in this scenario, each User object contains update about the same user
        public SomeViewModel(IObservable<User> user, IReactiveCreator observed){
            IsActive = observed.Propery(false); //automatically get uidispatcher
            FamilyName = user.Select(u => u.FamilyName).ToReactiveProperty(observed.OnDispatcher);
            Name = user.Select(u => u.Name).ToReactiveProperty(observed.OnDispatcher);
            NameOfUser = user
                .ObservedOn(observed.OnTaskScheduler) //push to background to do some heavy work
                .Select(CalculateAge)
                .ToReactiveProperty(observed.OnDispatcher);
            DeleteUser = observed.Command();
            DeleteUser.
               .Do(invokation => DeleteUserInDatebase())
               .Subscribe()
        }
        ...
    }
````
In my opinion this offers a more fluent API while creating reactive properties. My IReactiveCretor implementation uses a ITestSchedulerService that can be easily mocked in tests. 

What do you think?

**Comment by runceel** [comment]
I think IReactiveCreator is almost same feature as IScheduler.

```cs
public SomeViewModel(IObservable<User> user, IScheduler scheduler) 
{
    ....
    FamilyName = user.Select(u => u.FamilyName).ToReactiveProperty(scheduler);
    ....
    DeleteUser = new ReactiveCommand(scheduler);
    ....
}
```
And UIDispatcherScheduler can run process on custom thread.

```cs
class MySyncContext : SynchronizationContext
{
    // override Send and Post methods
}

// some test class
[AssemblyInitialize]
public static void Init(TestContext context)
{
    SynchronizationContext.SetSynchronizationContext(new MySyncContext());
}
```

**Comment by runceel** [comment]
This update contains following change(s).

* Add `ReactivePropertyScheduler` become an alternative to `UIDispatcherScheduler`

`ReactivePropertyScheduler` provides `SetDefault` method to change default `IScheduler`. You can use it like following.

```cs
var s = new TestScheduler();
ReactivePropertyScheduler.SetDefault(s);
var viewModel = new SampleViewModel();
viewModel.Name.Value = "Hoge"; // use TestScheduler.
s.AdvancedBy(10);
// your assertion.
```

What do you think?

**Comment by dscopra** [comment]
I think the result (in production code) is the same, but I think my solution is more explicite. But there is a problem in test code:
In your solution I set the scheduler in one test and it is used within all tests, that don't reset it (due to its static nature). So depending on the order the tests are executed, the result may differ and test might unexpectedly fail. My solution, each ViewModel explicitly demands to provide a IReactiveCreator (and therefor the correct scheduler) in each test. 

The interesting part of my solution is, that you can use it side-by-side with yours.

**Comment by BADF00D** [comment]
I think the result (in production code) is the same, but I think my solution is more explicite. But there is a problem in test code:
In your solution I set the scheduler in one test and it is used within all tests, that don't reset it (due to its static nature). So depending on the order the tests are executed, the result may differ and test might unexpectedly fail. My solution, each ViewModel explicitly demands to provide a IReactiveCreator (and therefor the correct scheduler) in each test.

The interesting part of my solution is, that you can use it side-by-side with yours.

**Comment by xin9le** [comment]
Thank you for your suggestion.

We wanna rethink your solution.
Could you show us your `IReactiveCreator` implementation (if you can).

Best regards,

**Comment by BADF00D** [comment]
```csharp
   public interface IReactiveCreator {
		ISchedulerProvider Schedulers { get; }
		ReactiveCollection<T> Collection<T>();
		ReactiveCollection<T> Collection<T>(IObservable<T> observable);
		ReactiveProperty<T> Property<T>(T intial_value = default(T));

		ReactiveCommand Command();

		ReactiveCommand<T> Command<T>();

		IScheduler OnDispatcher { get; }

		IScheduler OnTaskPool { get; }
	}
    public class ReactiveCreator : IReactiveCreator {
		public ReactiveCreator(ISchedulerProvider schedulers) {
			Schedulers = schedulers;
			OnDispatcher = schedulers.Dispatcher;
			OnTaskPool = schedulers.TaskPool;
		}

		public ISchedulerProvider Schedulers { get; private set; }

		public ReactiveCollection<T> Collection<T>() {
			return new ReactiveCollection<T>(Schedulers.Dispatcher);
		}

		public ReactiveCollection<T> Collection<T>(IObservable<T> observable) {
			return new ReactiveCollection<T>(observable, Schedulers.Dispatcher);
		}

		public ReactiveProperty<T> Property<T>(T intial_value = default(T)) {
			return new ReactiveProperty<T>(Schedulers.Dispatcher, intial_value);
		}

		public ReactiveCommand Command() {
			return new ReactiveCommand(Schedulers.Dispatcher);
		}

		public ReactiveCommand<T> Command<T>() {
			return new ReactiveCommand<T>(Schedulers.Dispatcher);
		}

		public IScheduler OnDispatcher { get; }
		public IScheduler OnTaskPool { get; }
	}
    public interface ISchedulerProvider
	{
		IScheduler CurrentThread { get; }
		IScheduler Dispatcher { get; }
		IScheduler Immediate { get; }
		IScheduler NewThread { get; }
		IScheduler TaskPool { get; }
		IScheduler ThreadPool { get; }
		IScheduler NewEventLoopScheduler { get; }
	}
````

**Comment by runceel** [comment]
hmm.

I think that it is same that.

```cs
public SomeViewModel(IScheduler onDispatcher, ISchesuler onTaskPool)
{
    // initial code
}
```

Many useful factory method is good. But I think that it have higher learning cost. I prefer normal constructor (using IScheduler) than your suggestion (using IReactiveCreator).

**Comment by BADF00D** [comment]
I prefer less parameters(and therefore composite objects), but I thinks it's a matter of taste.

I'm going to make a separate library extending yours. 
Thanks for your feedback.

**Comment by xin9le** [comment]
Will you release its extended library as open source?
Please let us know if completed.
We will add your library to readme.md.

Thank you very much for your feedback!!
Best regards,
