### ISSUE TITLE
ReactiveProperty<T> doesn't raise PropertyChanged when HasErrors changes.

### ISSUE THREAD

**Issue by SittenSpynne** [runceel/ReactiveProperty#188]
I have a control on my view that has a boolean property `HasErrors`. I noticed ReactiveProperty has a property like that and implements INotifyPropertyChanged, so I expected if I bind my control's property to the ReactiveProperty's property, they would stay in sync.

Today I determined the ReactiveProperty never raises its event when `HasErrors` changes. So I have to take the clunkier approach of making a separate property depend on `ObserveErrors`. It'd be nice if I could bind to `HasErrors`, and technically ReactiveProperty isn't following the INotifyPropertyChanged contract.

**Comment by runceel** [comment]
@SittenSpynne 
Thank you for the feedback.
I'm sure that your feedback is make sense.
I'll fix it.

**Comment by runceel** [comment]
@SittenSpynne 
I have just published v7.4.1 to NuGet.
Please check it.

If you found issues related to this, then please re-open or create a new issue.
