### ISSUE TITLE
Question regarding cleanup / Dispose

### ISSUE THREAD

**Issue by danielmue** [runceel/ReactiveProperty#19]
Hi,

Thanks for this great library!

I've just checked your examples and wonder how you clean up / unsubscribe from observables. Both `ReactiveCommand` and `ReactiveProperty<T>` implement the `IDisposable` interface. It is however not mentioned (or implemented) in any example.

I think the `ToReactiveProperty<T>(this IObservable<T> source, ..)` extension method requires the resulting property instance to be disposed - if not longer needed. Otherwise I would expect serious memleaks, if the application creates / destroys a lot of view models.

What do you think? Any best practices we should take into account?

Thanks,
Daniel

**Comment by runceel** [comment]
Hi, @danielmue.

We're sorry, because of our poor sample.
We think it can be resolved using `CompositeDisposable` and `AddTo` extension method.
Please see also.

```cs
private CompositeDisposable Disposabele { get; } = new CompositeDisposable();

public ReactiveProperty<string> PropA { get; }
public ReactiveProperty<string> PropB { get; }

public Ctor() 
{
    // collect IDisposable
    this.PropA = fooObservable.ToReactiveProperty().AddTo(this.Disposable);
    this.PropB = barObservable.ToReactiveProperty().AddTo(this.Disposable);
}

public void SomeCleanupMethod()
{
    this.Disposable.Dispose(); // cleanup all!
}
```

**Comment by danielmue** [comment]
Ah, okay. That means you MUST dispose ReactiveProperties and the library ships a fluent syntax (`.AddTo(..)`) for this.

Great, thanks!

**Comment by runceel** [comment]
Hi! @danielmue.

We updated Englishi documentation.
https://github.com/runceel/ReactiveProperty/blob/master/README.md

Please show.(We wrote dispose case.)

Thank you.
