### ISSUE TITLE
New namespace discussion

### ISSUE THREAD

**Issue by xin9le** [runceel/ReactiveProperty#2]
## Motivation
Current name space is 'CodePlex.Reactive.Xxx'. But now, our project was moved to GitHub. It's ridiculous for us anymore. So, we are planning to change name space in ReactiveProperty version 2.

## Help us
We are looking for some good ideas. Please tell us your idea :)

**Comment by runceel** [comment]
ReactiveLight, ReactiveFoundationClasses, ReactiveXin9le, ReactiveOkazuki...mmm...

**Comment by xin9le** [comment]
ReactiveStars

**Comment by runceel** [comment]
Coral.Reactive

**Comment by amay077** [comment]
My suggestions are

* ReactiveProps
* ReactiveBindings

**Comment by xin9le** [comment]
Thanks @amay077! Your suggestions are so cool. We will adopt your idea 'ReactiveBindings'. Next new namespace will be ***Reactive.Bindings***. Please look foward to release ReactiveProperty vNext!!
