### ISSUE TITLE
Replace Subject -> ReplaySubject

### ISSUE THREAD

**Issue by tbdbj** [runceel/ReactiveProperty#20]
GetLatestOnSubsribe can be easy done by using new ReplaySubject(1).

**Comment by runceel** [comment]
Thank you for your suggestion.

We understand that source code is kept more simpler to apply your suggestion than ours. However, ReplaySubject has one performance issue. It is slower than Subject.

Following is performance test result.

800ms : ReplaySubject
500ms : Subject

So we decided to use Subject.
