### ISSUE TITLE
Integration/merge with ReactiveIU

### ISSUE THREAD

**Issue by SuperJMN** [runceel/ReactiveProperty#21]
Hello! I'm taking a look to your project. I come from a very interesting project called ReactiveUI. The only problem with it is that it doesn't provide a handy way to handle validation. 

Do you know that project? Maybe you could join efforts to merge both projects, since both of you attack almost the same problems. For instance, you also have a ReactiveCommand.

Please, take a look: https://github.com/reactiveui/ReactiveUI

Best regards!

**Comment by runceel** [comment]
Thank you for your suggenstion.

However, our library concept is that ViewModel doesn't have base class.
ReactiveUI expects inheritance.

For this reason, we have no plan to merge.
Sorry.
