### ISSUE TITLE
AsyncCommand.Execute() を await したい

### ISSUE THREAD

**Issue by p4j4dyxcry** [runceel/ReactiveProperty#216]
いつも便利に使わせていただいております。
さて、表題の件なのですが、何か良い方法はありますでしょうか？

ソースコードを見てたのですが、以下のようにAsyncCommand<T>.Executeがasync void になっているのでTaskが戻り値として利用できるようになればいいのかな？と思っています。
AsyncReactiveCommand.cs #149付近
``` 
        /// <summary>
        /// Push parameter to subscribers, when executing CanExecuting is changed to false.
        /// </summary>
        public async void Execute(T parameter)
        {
            if (isCanExecute)
            {
                canExecute.Value = false;
                var a = asyncActions.Data;
```
もし、別の方法で待てるならそれでも良いと考えています。

待ちたい理由なのですがアプリから実行する場合非同期で良いのですが、UnitTestでは同期的に実行したいのが目的です。

以上、よろしくお願いします。

**Comment by runceel** [comment]
PR 作って ExecuteAsync メソッドを追加しておきました。
これでイメージ通りですか？

近いうちにリリース作業を行います。

**Comment by runceel** [comment]
あと、待つだけなら AsyncReactiveCommand に Subscribe で渡してるメソッド自体を呼べば一応待つことも出来ます。

**Comment by p4j4dyxcry** [comment]
@runceel 
対応ｂありがとうございます、イメージ通りです。

>あと、待つだけなら AsyncReactiveCommand に Subscribe で渡してるメソッド自体を呼べば一応待つことも出来ます。
アドバイスありがとうございます！今回のユースケースでは利用できないのでリリースを待とうと思います。

**Comment by runceel** [comment]
@p4j4dyxcry 
PR マージしたので。このIssueがクローズされてしまいましたが 7.6.0 をリリースしました。
