### ISSUE TITLE
Support debug symbol

### ISSUE THREAD

**Issue by tmori3y2** [runceel/ReactiveProperty#23]
こんにちは。NuGet Packageに.pdbファイルを追加することを検討していただけないでしょうか？

理由は、ステップインしてデバッグすることで、ReactivePropertyへの理解を深めるためです。
もちろん、自分でソースを落としてビルドすれば出来るのはわかっていますが、標準で配布されていれば「My Codeのみにステップイン」のチェックを外すだけでステップイン出来るので、かなり利用する側の負担が減ると思われます。

方法は２つあると思います。

* dll/xmlと一緒に配布する方法
    * OxyPlotとかはこの方法で含めています
    * http://docs.nuget.org/create/nuspec-reference#specifying-files-to-include-in-the-package
    * 公式DocはDebugビルドの.pdbの例ですが、Releaseビルドで.pdbを出力して添付していただければステップインできます
* nuget pack -Symbols
   * http://docs.nuget.org/consume/command-line-reference#pack-command-usage
   * https://docs.nuget.org/create/creating-and-publishing-a-symbol-package
   * http://www.symbolsource.org/Public/Wiki/Index
   * .pdb無しのnuget.org用、アリのsymbolsource.org用の.nupkgを作って、いろいろごにゅごにょするらしいです。

nuget.orgで一緒に配布する方法は、基本は.nuspecの修正で出来ます。

ただし、ReactiveProperty.Platform.iOSはReleaseで.pdbが出力されていなかったので修正が必要です。

githubで間違ってForkボタンを押してしまったので、ついでに修正してパッケージの作成まで試してみました。

https://github.com/tmori3y2/ReactiveProperty/commit/cbd347ad5632e8186d35963c26d05a513333f00b

では、良いお返事をお待ちしています。

PS.

Mono/Xamarinの素人でかなり悩んだので、一つ質問があります。

.dll.mdbがMono系のシンボルファイルのようですが、.pdbがあればパッケージをインストールしたMono/Xamarinのプロジェクトで.dll.mdbを生成してくれるのではないかと思うのですが、合っているでしょうか？

**Comment by runceel** [comment]
フィードバックありがとうございます。
あんまり中にもぐってみることを考えてなかったのですが、特にデメリットもないので取り入れてみたいと思うのですがプルリクエスト投げていただいてもいいですか？（コミット見た感じ特に問題なさそうに感じたので）

因みにPSの内容は、私さっぱりです…すいません。

**Comment by tmori3y2** [comment]
ありがとうございます。
Githubはまだ初心者なので、Pull Request調べてチャレンジします。

**Comment by runceel** [comment]
お待ちしてます～。
いったん閉じますね。何かあったら気軽に書き込んでください。
