### ISSUE TITLE
ObserveElementProperty、ObserveElementObservablePropertyを使用したい

### ISSUE THREAD

**Issue by kitunechan** [runceel/ReactiveProperty#255]
v2.1.6にて
・INotifyCollectionChanged の拡張メソッドとして提供されていた ObserveElementProperty メソッドのアクセシビリティを internal にしました。
ということでしたが、自作のINotifyCollectionChangedにも利用したいため再度Publicにはならないでしょうか？

https://github.com/runceel/ReactiveProperty/blob/f5b87276d177c9350cb7830758454a36c77ba282/Source/ReactiveProperty.NETStandard/Extensions/INotifyCollectionChangedExtensions.cs#L113

https://github.com/runceel/ReactiveProperty/blob/f5b87276d177c9350cb7830758454a36c77ba282/Source/ReactiveProperty.NETStandard/Extensions/INotifyCollectionChangedExtensions.cs#L154

**Comment by runceel** [comment]
@kitunechan 

`internal` のものを `public` に公開にする PR は作成しました。マージは少々お待ちください。
`public` になったメソッドを使って以下のような拡張メソッドをご自身で定義していただくことで `ObservableCollection<T>` と同じ感覚で自作コレクションでも `ObservabeElementProperty` などのメソッドが使えるようになると思います。

```csharp
public static class MyCollectionExtensions
{
  public static IObservable<PropertyPack<TElement, TProperty>> ObserveElementProperty<TElement, TProperty>(this MyCollection<TElement> source, Expression<Func<TElement, TProperty>> propertySelector, bool isPushCurrentValueAtFirst = true)
    where TElement : class, INotifyPropertyChanged =>  
    CollectionUtilities.ObserveElementProperty(source, propertySelector, isPushCurrentValueAtFirst);
}
```

**Comment by runceel** [comment]
v7.9.0 のリリース作業に入りました。
@kitunechan 

独自コレクションクラスに `ObserveElementProperty` などの拡張メソッドが必要な場合は `Reactive.Bindings.Helpers.CollectionUtilities` クラスを利用して拡張メソッドを定義してください。

定義方法は `ObservableCollection<T>` 用に定義している以下のコードを参考にしてください。

https://github.com/runceel/ReactiveProperty/blob/main/Source/ReactiveProperty.NETStandard/Extensions/ObservableCollectionExtensions.cs#L72-L105

**Comment by kitunechan** [comment]
使い方まで考えていただきありがとうございます。😆
