### ISSUE TITLE
ReactivePropertyでクラスダイアグラムを使いたい。

### ISSUE THREAD

**Issue by kenichi-kobayashi** [runceel/ReactiveProperty#263]
Visual StudioのClass Diagramの機能を使った設計をしたいと考えています。

![image](https://user-images.githubusercontent.com/47070699/119903572-d92a9680-bf83-11eb-891f-6ffab82eefdf.png)

Class Diagramでは、上記のように、クラスとクラスの関係を視覚化することができます。
ReactivePropertyを使ったプロジェクトの場合、2点、困ったことがあります。

**① ReacitveCollection<T>を正しく認識してくれない。**

Class Diagramでは、「コレクションの関連として表示」という機能を使うことで、コレクションを解釈して、上図のように、クラス図の関係線を結んでくれます。

![image](https://user-images.githubusercontent.com/47070699/119903811-3cb4c400-bf84-11eb-900b-1d8af12af866.png)

こちらで実験してみたところ、以下のコレクションは正しく解釈して、関係線を結んでくれました。
        public MyItem[] ItemsArray { get; set; }
        public List<MyItem> ItemsList { get; set; }
        public Collection<MyItem> ItemsCol { get; set; }
        public ObservableCollection<MyItem> ItemsObservable { get; set; }
        public Dictionary<string, MyItem> ItemsDic { get; set; }
        public ReadOnlyCollection<MyItem> ItemsROC { get; set; }
        public IEnumerable<MyItem> ItemsIE { get; set; }
        public IFilteredReadOnlyObservableCollection<MyItem> ItemsIFRORC { get; set; }

しかし、なぜか以下のコレクションにおいては、正しく解釈できないようでエラーになってしまいます。
        public ReactiveCollection<MyItem> ItemsRC { get; set; }
        public ReadOnlyReactiveCollection<MyItem> ItemsRORC { get; set; }

![image](https://user-images.githubusercontent.com/47070699/119904020-9c12d400-bf84-11eb-923e-e4ad21c13d86.png)

**② ReactiveProperty<T>のTを認識してくれない。**

Visual StudioのClass Diagramでは、各プロパティとは、以下のような関係を結ぶことができます。

public MyViewModel MyViewModel {get; set;}

![image](https://user-images.githubusercontent.com/47070699/119905065-7090e900-bf86-11eb-9052-d1635378539a.png)

POCOのプロパティにおいては、上記のように認識してくれるのですが、Rp<T>の場合は、以下の通りになってしまいます。(当然といえば、当然なのですが)

public ReactiveProperty<MyViewModel> MyViewModelRp { get; set; }

![image](https://user-images.githubusercontent.com/47070699/119905147-9b7b3d00-bf86-11eb-8414-c9f162c0145f.png)

なんとか、直接、`<T>`と関係線を結ぶことはできないでしょうか？

上記の①も②も、RPプロジェクト側というよりかは、VisualStudioのClass Diagram機能側の都合だとは思うのですが、何か回避する方法を思いついたりしませんか？

**Comment by runceel** [comment]
## 1 について

これは ObservableCollection や ReadOnlyObservableCollection を継承しているだけなので原因不明です。

## 2 について

これも仕方ないと思います。


どちらも、Visual Studio の Class Diagram 機能の挙動なので、それのために ReactiveProperty の何かを変えるつもりは今のところありません。ただ、凄く少ない手間で特殊な参照などを追加せずに対応可能な方法があるのであれば PR があればマージすると思います。

**Comment by runceel** [comment]
一旦クローズにします。何か進展がある場合は別 Issue か再オープンとともにコメントお願いします。
