### ISSUE TITLE
ReactivePropertyWpfSchedulerがコンパイルエラーになってしまう。

### ISSUE THREAD

**Issue by kenichi-kobayashi** [runceel/ReactiveProperty#265]
ReactiveProperty V7.11.0をNugetから取得して、「ReactivePropertyWpfScheduler」を使おうと思ったのですが、
以下の通り、エラーになってしまいます。

![image](https://user-images.githubusercontent.com/47070699/122073356-5171d280-ce33-11eb-94bf-6405b1706e1b.png)

何が原因かわかりますでしょうか？

**Comment by runceel** [comment]
`ReactivePropertyWpfScheduler` は WPF 固有クラスなので使う場合は ReactiveProperty ではなく ReactiveProperty.WPF パッケージを NuGet からプロジェクトに追加してください。
ReactiveProperty パッケージは ReactiveProperty.WPF を追加すると自動的に追加されるので明示的に追加する必要はありません。

**Comment by kenichi-kobayashi** [comment]
そういうことですね。
いままで、WPF無しの無印を使ってしまっていました。
ありがとうございます。
