### ISSUE TITLE
ReactivePropertyWpfSchedulerを取り込むことでのアプリ側の影響について

### ISSUE THREAD

**Issue by kenichi-kobayashi** [runceel/ReactiveProperty#266]
こんにちわ。

いつも大変、便利に使わせてもらっています。
7.10.0のReactivePropertyWpfScheduler の追加に伴って、アプリ側の取り込みを実施しています。

ReactivePropertyWpfScheduler 
により、ObserverOnUIDispacherが不要になるように思っていましたが、どうでしょうか？
具体的には、以下のようなコードです。

PartsArea.SelectedItem.Throttle(TimeSpan.FromSeconds(0.5)).Where(a => a != null).ObserveOnUIDispatcher().Subscribe(async b => await updateChart()); 

実験してみましたが、ReactivePropertyWpfSchedulerを使う前後での変化はありませんでした。

ReactivePropertyWpfSchedulerを使った場合のアプリ側の影響は、どのようなものがありますでしょうか？

よろしくお願いします。

**Comment by runceel** [comment]
> ReactivePropertyWpfScheduler
> により、ObserverOnUIDispacherが不要になるように思っていましたが、どうでしょうか？

提示していただいたコードに関して言うと `ReactivePropertyWpfScheduler` を設定しても特に変わりありません。

### ReactivePropertyWpfScheduler を設定したときに起きること

WPF の App クラスの Dispatcher に紐づくスレッドで ReactiveProperty/ReadOnlyReactiveProperty/ReactiveCollection/ReadOnlyReactiveCollection の PropertyChanged や CollectionChanged イベントを発行するだけです。

ReactivePropertyWpfScheduler を設定しない場合は SynchronizationContextScheduler が使われます。ただ、このスケジューラーを使うと UI スレッド上でプロパティの変更があった場合も一旦イベントの発行をキューイングして遅れたタイミングでイベントを発行していたため WPF のバリデーションエラー時の UI の表示がうまくいかないケースがありました。
ReactivePropertyWpfScheduler は、UI スレッド上でのプロパティの変更があった場合は即座にイベントを発行する違いがあります。

関連 Issue: https://github.com/runceel/ReactiveProperty/issues/258

**Comment by kenichi-kobayashi** [comment]
なるほど。早速の回答ありがとうございます。

了解しました。
アプリ側では、本バージョンの取り込みにおいても、とくに問題がない限りは、修正する必要はなさそうですね。

ありがとうございました！
