### ISSUE TITLE
ToReactiveProperty() returns {null}

### ISSUE THREAD

**Issue by dhq-boiler** [runceel/ReactiveProperty#272]
Hi.
I've encountered a situation where ToReactiveProperty() always returns {null} within a particular method, so I'll report it.

I use ReactiveProperty 7.11.0 in this repository.

[Where]
This happens with the latest commit in the develop branch of my repository.
* GitHub
https://github.com/dhq-boiler/boiler-s-Graphics
* git repository
https://github.com/dhq-boiler/boiler-s-Graphics.git
* branch : develop
* commit : d183347
DiagramViewModel.cs line.359-375
```
        private void ExecuteClipCommand()
        {
            var picture = SelectedItems.OfType<PictureDesignerItemViewModel>().First();
            var pictureRP = picture.ToReactiveProperty(mode: ReactivePropertyMode.RaiseLatestValueOnSubscribe); //戻り値が何故か {null} になる
            var other = SelectedItems.OfType<DesignerItemViewModelBase>().Last();
            var pathGeometry = GeometryCreator.CreateRectangle(other as NRectangleViewModel, picture.Left.Value, picture.Top.Value);
            (pictureRP.Value.Sender as PictureDesignerItemViewModel).Clip.Value = pathGeometry;
            (pictureRP.Value.Sender as PictureDesignerItemViewModel).ClipObject.Value = other;
            pictureRP.Zip(pictureRP.Skip(1), (Old, New) => new { OldItem = Old, NewItem = New }).Subscribe(x =>
            {
                var _other = picture.ClipObject.Value;
                var _pathGeometry = GeometryCreator.CreateRectangle(_other as NRectangleViewModel, picture.Left.Value, picture.Top.Value, x.OldItem, x.NewItem);
                picture.Clip.Value = _pathGeometry;
            })
            .AddTo(_CompositeDisposable);
            Items.Remove(other);
        }
```
[How to reproduce]
1. Start debugging boilersGraphics
2. Draw any image with the image tool.
3. Draw any rectangle with the Reactangle tool.
4. Shift-click to select an image and then a rectangle.
5. In Menu, select "キャンバス(C)" -> "クリップを設定"
6. This is where ExecuteClipCommand() in DiagramViewModel.cs is called.
![how_to_reproduce](https://user-images.githubusercontent.com/7916855/126176074-3f711c87-9611-4ad5-bd06-418c72e94e3a.gif)

Thank you.

**Comment by runceel** [comment]
This is by design.

DesignerItemViewModel is implemented `IObservable<TransformNotification>`. In this case, `var pictureRP = picture.ToReactiveProperty(mode: ReactivePropertyMode.RaiseLatestValueOnSubscribe);` calls `public static ReactiveProperty<T> ToReactiveProperty<T>(this IObservable<T> source, T initialValue = default, ReactivePropertyMode mode = ReactivePropertyMode.Default, IEqualityComparer<T> equalityComparer = null);` extension method on `Reactive.Bindings.ReactiveProperty` static class.
If `DesignerItemViewModel` published a value to `IObservable` sequence, then `ReactiveProperty` could detect the value. But your implementation has never called `OnNext` on `Subscribe` method.

```csharp:DesignerItemViewModelBase.cs
        private List<IObserver<TransformNotification>> _observers = new List<IObserver<TransformNotification>>();

        public IDisposable Subscribe(IObserver<TransformNotification> observer)
        {
            _observers.Add(observer);
            return new DesignerItemViewModelBaseDisposable(this, observer);
        }
```

**Comment by dhq-boiler** [comment]
Thank you for answering.
After fixing it as you said, ToReactiveProperty() no longer returns null.

```csharp
        private List<IObserver<TransformNotification>> _observers = new List<IObserver<TransformNotification>>();

        public IDisposable Subscribe(IObserver<TransformNotification> observer)
        {
            _observers.Add(observer);
+           _observers.ToList().ForEach(x => x.OnNext(new TransformNotification()
+           {
+               Sender = this
+           }));
            return new DesignerItemViewModelBaseDisposable(this, observer);
        }
```

**Comment by runceel** [comment]
@dhq-boiler 

You don't need calling `OnNext` for all observers on Subscribe method, to call `OnNext` to an instance of IObserver on the argument like below:
```csharp
        private List<IObserver<TransformNotification>> _observers = new List<IObserver<TransformNotification>>();

        public IDisposable Subscribe(IObserver<TransformNotification> observer)
        {
            _observers.Add(observer);
+          observer.OnNext(new TransformNotification()
+          {
+              Sender = this
+          });
            return new DesignerItemViewModelBaseDisposable(this, observer);
        }

```

**Comment by dhq-boiler** [comment]
Thank you for telling me everything.
I fixed this.
