### ISSUE TITLE
EventToReactiveCommandのDispatcherについて

### ISSUE THREAD

**Issue by mxwl-dev** [runceel/ReactiveProperty#276]
お世話になります。
RactiveProperty使わせて頂いております。

WPFのEventToReactiveCommandなのですが、
ObserveOnUIDispatcher()でUIスレッドに転送されているために
WindowのClosingイベントに使用するとWindowが閉じられた後にCommandが呼ばれてしまいます。

UIスレッドに転送しないようにするプロパティなどを追加出来ないでしょうか?

**Comment by runceel** [comment]
ありがとうございます。
これは ReactivePropertyScheduler に設定されているデフォルトのスケジューラーにディスパッチすべきですね…

デフォルトはReactivePropertySchedulerにディスパッチしつつオプションでディスパッチをオフにするプロパティを追加しようと思います。

**Comment by runceel** [comment]
デフォルトのディスパッチ先を `ReactivePropertyScheduler.Default` に変更しました。
WPF アプリであれば `ReactivePropertyWpfScheduler` を `ReactivePropertyScheduler.SetDefault` を使って設定していれば UI スレッド上にいる場合は即座に処理が呼び出されるようになっていると思います。

もし、常に現在のスレッド上で呼び出したい場合は `EventToReactiveCommand` の `CallExecuteOnScheduler` プロパティを `false` に設定してください。

**Comment by mxwl-dev** [comment]
ありがとうございます。
`ReactivePropertyScheduler.SetDefault`または`CallExecuteOnScheduler`を使うことで想定している動作になりました。
