### ISSUE TITLE
About usage of ToReactiveCommand()

### ISSUE THREAD

**Issue by Yukimune** [runceel/ReactiveProperty#28]
I'm studying and run some examples on your site.  It's very useful.
http://blog.okazuki.jp/entry/2015/02/22/212827

In the "Command at Reactive Property" section.
Yes, I could run your example.
Then, I've tried another type of ToReactiveCommand(), but my example doesn't work as expected.

What any problem in my source?
Buttons(Command1,2) doesn't change their appearance by CanExecuteChanged event.
But I can catch CanExecuteChanged event (Command1,2) every time boolSource.Value changes.

MainWindow.xaml

    <Window.DataContext>
        <local:MainWindowViewModel></local:MainWindowViewModel>
    </Window.DataContext>
    <Grid>
        <StackPanel>
            <Button Content="Button1" Command="{Binding Command1}"/>
            <Button Content="Button2" Command="{Binding Command2}"/>
            <Button Content="Switch" Command="{Binding SwitchButton}"/>
        </StackPanel>
    </Grid>

MainWindow.xaml.cs

    public partial class MainWindow : Window
    {
        public MainWindow()
        {
            InitializeComponent();
        }
    }

    public class MainWindowViewModel
    {
        private ReactiveProperty<bool> boolSource { get; } = new ReactiveProperty<bool>(false);

        public ReactiveCommand Button1 { get; }
        public ReactiveCommand Button2 { get; }
        public ReactiveCommand SwitchButton { get; }
        public MainWindowViewModel()
        {
            Button1 = boolSource.ToReactiveCommand();            
            Button1.CanExecuteChanged += (s, e) => { System.Diagnostics.Debug.WriteLine("changed1"); };

            Button2 = new ReactiveCommand(boolSource);
            Button2.CanExecuteChanged += (s, e) => { System.Diagnostics.Debug.WriteLine("changed2"); };

            SwitchButton = new ReactiveCommand();
            SwitchButton.Subscribe(_ => { boolSource.Value = !boolSource.Value; });
        }
    }

Thank you!

**Comment by Yukimune** [comment]
ReactiveProperty is 2.8.0 and TargetFramework Version is 4.6.1 I'm using.

**Comment by runceel** [comment]
I think that this program is having typo.

```xml
<Window.DataContext>
    <local:MainWindowViewModel></local:MainWindowViewModel>
</Window.DataContext>
<Grid>
    <StackPanel>
        <Button Content="Button1" Command="{Binding Button1}"/> <!-- here -->
        <Button Content="Button2" Command="{Binding Button2}"/><!-- here ->
        <Button Content="Switch" Command="{Binding SwitchButton}"/>
    </StackPanel>
</Grid>
```

**Comment by Yukimune** [comment]
Oh, I'm sorry, really, I'm so embarrassed. It's solved.
