### ISSUE TITLE
ReadOnlyReactivePropertySlim does not notify via linked ForceNotify

### ISSUE THREAD

**Issue by josephnarai** [runceel/ReactiveProperty#283]
I would like to report a bug in ReactivePropertySlim... code below:

using Reactive.Bindings;
using System;
using System.Diagnostics;

public class ReactivePropertySlimTest
{
    private ReactivePropertySlim<double[]> _Values { get; }
    public ReadOnlyReactivePropertySlim<double[]> Values { get; private set; }
    private IDisposable _Subscription;

    public ReactivePropertySlimTest()
    {
        _Values = new ReactivePropertySlim<double[]>(new double[2]);
        Values = _Values.ToReadOnlyReactivePropertySlim(_Values.Value);
        _Subscription = Values.Subscribe(SetData); // This will call SetData as it should

        _Values.ForceNotify();  // This won't call SetData as it should
    }

    ~ReactivePropertySlimTest()
    {
        _Subscription?.Dispose();
    }

    private void SetData(double[] values)
    {
        Debug.WriteLine("SetData");
    }
}

If I change to ReactiveProperty - it works as expected - however my use case wants to use Slim, as it's very time sensitive, so the performant version is prefered. For now, I just won't bother with the ReadOnly transfer and I'll just take care not to set Value!

**Comment by soi013** [comment]
As far as a quick look, the following changes might solve the problem.

```
Values = _PeakdBValues.ToReadOnlyReactivePropertySlim(_PeakdBValues.Value);
👇
Values = _PeakdBValues.ToReadOnlyReactivePropertySlim(_PeakdBValues.Value, ReactivePropertyMode.RaiseLatestValueOnSubscribe);
```

Not sure about the details of `_PeakdBValues`. If it is created in the same way as `Values`, the same change is needed.

**Comment by josephnarai** [comment]
Ah, sorry, stuffed up my pseudo code... I'll post actual code in a minute.

However, I can say I've tried all the combos of  ReactivePropertyModes and nothing works... as I mentioned, I just change from a ReactivePropertySlim to ReactiveProperty for both and it all works as expected.

**Comment by josephnarai** [comment]
Ok, I've updated the pseudo code in my original post to actual code... Hope that helps you track it down :)

**Comment by soi013** [comment]
In my environment, changing to `ReactivePropertyMode.RaiseLatestValueOnSubscribe` solved the problem.

`SetData()` is called from `Values.Subscribe(...) `and `_Values.ForceNotify()`.
Conversely, changing `_Values` to `ReactiveProperty` did not change the behavior.

My environment is as follows.

```
ReactiveProperty Version="7.12.0"
net5.0-windows
<UseWPF>true
<Nullable>enable
```

**Comment by josephnarai** [comment]
Oh, that does fix it for me too. However the default case should be DistinctUntilChanged | RaiseLatestValueOnSubscribe

So I don't understand why ForceNotify() should be affected by DistinctUntilChanged ?

**Comment by soi013** [comment]
In the unmodified code, `_Values.ForceNotify()` is still notifying.
However, if `DistinctUntilChanged` is enabled in `Values`, `Values` will ignore a second notification of the same value from `_Values`. Therefore, `SetData()` will be called only once.

The following changes will also cause `SetData()` to be called twice.

````
Values.Subscribe(SetData)
👇
_Values .Subscribe(SetData)
```

**Comment by josephnarai** [comment]
No, _Values is private, so SetData should only be subscribed from the public Values...

I now understand why DistinctUntilChanged affects ForceNotify() not acutally notifying... however it's not really an obvious behaviour...

Thanks for helping me out... I have a solution that works now.

**Comment by soi013** [comment]
> DistinctUntilChanged affects ForceNotify()

No. 'DistinctUntilChanged' does not affects 'ForceNotify()'.
'DistinctUntilChanged' affects 'Subscribe()'.

**Comment by josephnarai** [comment]
Well, it does... my understanding is that a call to ForceNotify() will end up calling anyone subscribed to a ReactiveProperty regardless of if a value is distinct... that's like the main reason you would want to call ForceNotify() ... to notify everyone of a change... 

But you are saying that DistinctUntilChanged means that a ForceNotify() won't notify any listeners if the value is the unchanged?

**Comment by soi013** [comment]
> ForceNotify() ... to notify **everyone**

It is extremely difficult.
`_Values.ForceNotify` can only be enforced up to the point where `_Values` fire notify, and it tells `Values`. `Values` and `_Values` are connected by rx pipe, but they are independent objects.

> But you are saying that having DistinctUntilChanged means that a ForceNotify() won't notify any listeners if the value is unchanged?

No. `_Values.ForceNotify()` will notify all listeners(`Values`) of `_Values`, but will not stop that lisener ignore notification from `_Values`.

> Values.Value = 1; 

`Values` is ReadOnlyRP. So, is it `_Values`?

```csharp
Values.ForceNotify() //-> should call SetData and will it
_Values.ForceNotify() //-> will not call SetData. Because Values will ignore notification, not _Values.
```

**Comment by josephnarai** [comment]
So because it's cascaded via the ToReadOnly... I understand and it makes sense, however as I mentioned, not immediately obvious.

Personally, I would prefer a simpler ReadOnly object, one where you can privately set the value, but not publically... that would simplify and remove the need for cascading ReactiveProperties altogether!

Thank you for taking the time to explain it to me - much appreciated.

**Comment by soi013** [comment]
> I would prefer a simpler ReadOnly object, one where you can privately set the value, but not publically

How about this? I use this idiom a lot.

```csharp
public IReadOnlyReactiveProperty<double[]> Values => _Values;
private readonly ReactivePropertySlim<double[]> _Values = new ReactivePropertySlim<double[]>(new double[2]);

public ReactivePropertySlimTest()
{
    Values.Subscribe(SetData);
    _Values.ForceNotify();
}
```

**Comment by josephnarai** [comment]
Yes, this is what I used too - althgouth I like the => operator, nice. I'll adopt it.

Thanks!

**Comment by josephnarai** [comment]
Actaully, a question - is the IReadOnlyReactiveProperty<> as efficient as the Slim? If not, I'll keep using my Slim version!

**Comment by soi013** [comment]
I'm not a performance expert, but it's clearly faster than ReactiveProperty (not Slim).
If the instance of `IReadOnlyReactiveProperty<T>` is `ReactivePropertySlim<T>`, the only difference is the call from outside of class via interface.

**Comment by josephnarai** [comment]
Oh, I see, That sounds ok to me! Thanks again.
