### ISSUE TITLE
IFilteredの元になっているObservableCollectionをClearすると、非常に稀に例外が出る

### ISSUE THREAD

**Issue by kenichi-kobayashi** [runceel/ReactiveProperty#286]
いつも、大変、お世話になっております。

以下の配列があります。

```cs
private ObservableCollection<DiffSensorModel> allItems;
```

これを元に、以下のとおり、複数のIFiltedを作りました。

```cs
TargetItems = allItems.ToFilteredReadOnlyObservableCollection(a => a.IsTarget).AddTo(disposables);
SelectedItems = allItems.ToFilteredReadOnlyObservableCollection(a => a.IsTarget && a.IsSelected).AddTo(disposables);
CheckedItems = allItems.ToFilteredReadOnlyObservableCollection(a => a.IsTarget && a.IsChecked.Value).AddTo(disposables);
FilteredCheckedItems = allItems.ToFilteredReadOnlyObservableCollection(a => a.IsTarget && a.IsChecked .Value&& a.IsFiltered).AddTo(disposables);
```

この状態で、
```cs
allItems.Clear();
```
を実行すると、後述の例外が発生することが、非常に稀にあります。

この情報から、原因の手がかりを見つけることはできますでしょうか？

```
System.ArgumentOutOfRangeException: インデックスが範囲を超えています。負でない値で、コレクションのサイズよりも小さくなければなりません。
--
パラメーター名:index
場所 System.ThrowHelper.ThrowArgumentOutOfRangeException(ExceptionArgument argument, ExceptionResource resource)
場所 Reactive.Bindings.Helpers.FilteredReadOnlyObservableCollection`2.<>c__DisplayClass23_0.<.ctor>b__0(SenderEventArgsPair`2 x)
場所 System.Reactive.ObserverBase`1.OnNext(T value)
場所 System.Reactive.AutoDetachObserver`1.OnNextCore(T value)
場所 System.Reactive.ObserverBase`1.OnNext(T value)
場所 System.Reactive.ObserverBase`1.OnNext(T value)
場所 System.Reactive.AutoDetachObserver`1.OnNextCore(T value)
場所 System.Reactive.ObserverBase`1.OnNext(T value)
場所 System.ComponentModel.PropertyChangedEventHandler.Invoke(Object sender, PropertyChangedEventArgs e)
場所 System.Reactive.ObserverBase`1.OnNext(T value)
場所 Reactive.Bindings.ReactivePropertySlim`1.OnNextAndRaiseValueChanged(T& value)
場所 Reactive.Bindings.ReactivePropertySlim`1.set_Value(T value)
場所 System.Collections.Generic.List`1.ForEach(Action`1 action)
場所 System.Reactive.AnonymousSafeObserver`1.OnNext(T value)
場所 System.Reactive.Linq.ObservableImpl.Select`2.Selector._.OnNext(TSource value)
場所 System.Reactive.Linq.ObservableImpl.Where`1.Predicate._.OnNext(TSource value)
場所 System.Reactive.AutoDetachObserver`1.OnNextCore(T value)
場所 System.Reactive.ObserverBase`1.OnNext(T value)
場所 System.Collections.Specialized.NotifyCollectionChangedEventHandler.Invoke(Object sender, NotifyCollectionChangedEventArgs e)
場所 System.Collections.ObjectModel.ObservableCollection`1.OnCollectionChanged(NotifyCollectionChangedEventArgs e)
場所 System.Collections.ObjectModel.ObservableCollection`1.ClearItems()
場所 System.Reactive.AnonymousSafeObserver`1.OnNext(T value)
場所 System.Reactive.Linq.ObservableImpl.Select`2.Selector._.OnNext(TSource value)
場所 System.Reactive.Linq.ObservableImpl.Where`1.Predicate._.OnNext(TSource value)
場所 System.Reactive.AutoDetachObserver`1.OnNextCore(T value)
場所 System.Reactive.ObserverBase`1.OnNext(T value)
場所 System.Collections.Specialized.NotifyCollectionChangedEventHandler.Invoke(Object sender, NotifyCollectionChangedEventArgs e)
場所 Reactive.Bindings.Helpers.FilteredReadOnlyObservableCollection`2.<>c__DisplayClass23_0.<.ctor>b__1(NotifyCollectionChangedEventArgs x)
場所 System.Reactive.ObserverBase`1.OnNext(T value)
場所 System.Reactive.AutoDetachObserver`1.OnNextCore(T value)
場所 System.Reactive.ObserverBase`1.OnNext(T value)
場所 System.Collections.Specialized.NotifyCollectionChangedEventHandler.Invoke(Object sender, NotifyCollectionChangedEventArgs e)
場所 System.Collections.ObjectModel.ObservableCollection`1.OnCollectionChanged(NotifyCollectionChangedEventArgs e)
場所 System.Collections.ObjectModel.ObservableCollection`1.ClearItems()
```

**Comment by soi013** [comment]
提示されたコード自体には問題が無いように見えます。
原因となるところは別の場所にありそうなので、問題を再現する最小コードがほしいところですが、
非常に稀に発生するバグを再現するのは困難そうですね。

エラーメッセージ内に`ClearItems()`が2回出てきています。
`allItems`の変更通知を購読して、さらに`allItems.Clear()`を呼ばれるパターンがまれに発生しているのではないでしょうか？

**Comment by kenichi-kobayashi** [comment]
soi013さん、

早速のコメントありがとうございます。
そして、レスポンスが悪くてすいません。

>原因となるところは別の場所にありそうなので、問題を再現する最小コードがほしいところですが、
>非常に稀に発生するバグを再現するのは困難そうですね。
その通りなんですよね。
以下のような再現テストをするサンプルを作ってみましたが、再現してくれませんでした。

[ReactivePropertyTest.zip](https://github.com/runceel/ReactiveProperty/files/7125783/ReactivePropertyTest.zip)

過去に３回ほどは経験しているので、確実に何かがあるんだと思います。

>エラーメッセージ内にClearItems()が2回出てきています。
>allItemsの変更通知を購読して、さらにallItems.Clear()を呼ばれるパターンがまれに発生しているのではないでしょうか？
アプリ層では、一切、やっていませんね。

allItemsを観測しているのは、IFilterdのみですね。

うーん。
内部設計から何か気になるヒントなど頂けましたら、そこを起点に、もう少しこちらでも、実験してみたいですが、何か切り口が思いついたりしないでしょうか？

皆様のお知恵をお貸しください。

よろしくお願いします。

**Comment by soi013** [comment]
> 内部設計から何か気になるヒントなど頂けましたら、そこを起点に、もう少しこちらでも、実験してみたいですが、何か切り口が思いついたりしないでしょうか？

原因かは不明ですが、サンプルを見て気になった点としては、
PropertyChange.Fodyを使用しているので、`INotifyPropertyChanged`を継承しているクラスの書き換え可能なプロパティ`public xxx {get;set;}` には全て`PropertyChanged`呼び出しが挿入されるはずです。不要であれば、読み取り専用プロパティ`public xxx {get;}`にしたほうがよいでしょう。`MyItemsViewModel`の`FilteredX`など、ほとんどのプロパティは読み取り専用にできそうです。
特にReactivePropertyの場合は経験上、99％は読み取り専用になります。

**Comment by runceel** [comment]
@kenichi-kobayashi 
ちょっとだけ質問文で見た目を変えさせてもらいました。シンタックスハイライトとかが出るようにしただけなので文章はいじっていません。

質問ですが例外が出ているのは `ObservableCollection<T>` を使ってるコードで起きていますか？ #237 で行っていた `RangedObservableCollection<T>` ですか？
`RangedObservableCollection<T>` の場合は `FilteredReadOnlyObservableCollection` にバグを 1 つ見つけたので状況によっては `ArgumentOutOfRangeException` が起きるかもしれません。

`FilteredReadOnlyObservableCollection` の `OnCollectionChanged` では以下のように `Reset` イベントは `Clear` 呼び出し前提としているコードがあります。

```cs
private void OnCollectionChanged(NotifyCollectionChangedEventArgs e)
{
    switch (e.Action)
    {
        case NotifyCollectionChangedAction.Add:
            ItemsCount++;
            break;

        case NotifyCollectionChangedAction.Remove:
            ItemsCount--;
            break;

        case NotifyCollectionChangedAction.Reset:
            ItemsCount = 0; // Clear だから要素数は 0 になるという前提のコード
            break;
    }
    CollectionChanged?.Invoke(this, e);
}
```

ですが #237 の対応で `Reset` イベントの時も要素数は 0 とは限らないケースがあるため、内部管理のインデックスと実情が異なるケースが起こると考えられます。
まだコードをざっと見ただけなので確証はありませんが問題が起きているコードは `ObservableCollection<T>` を使っているのか、それとも `RangedObservableCollection<T>` を教えて頂けないでしょうか。

**Comment by kenichi-kobayashi** [comment]
soi013さん、回答ありがとうございます。
確かに、その通りですね。
今後の開発の参考にさせてもらいます。

runceelさん、返信ありがとうございます。

>シンタックスハイライトとかが出るようにしただけなので文章はいじっていません。

修正ありがとうございます。
不慣れなので、慣れていこうと思います。

>RangedObservableCollection<T> を教えて頂けないでしょうか。

RangedObservableCollectionは使っていません。
RangedObservableCollectionとは、こちらのことでしょうか？

https://github.com/mattleibow/RangedObservableCollection

RangedObservableCollectionにおいては、実験的に使ってみたことがあるんですが、ToFilteredが未対応であることは、コードのコメントにも記載があったし、動かしてみても100%エラーになったので、使えないと判断していました。

何か誤解している点があれば、ご指摘もらえるとありがたいです。

**Comment by runceel** [comment]
内部で行っているコレクション操作にロックを追加して矛盾が起きないようにガードするようにしてみようと思います。

**Comment by kenichi-kobayashi** [comment]
いつも、本当にありがとうございます！
お待ちしています。

**Comment by runceel** [comment]
@kenichi-kobayashi 
もう1つ伺いたいのですが `ObservableCollection<T>` への `Clear` の呼び出しのほかに `ObservableCollection<T>` や `IFilteredReadOnlyObservableCollection<T>` の要素のプロパティの書き換えを別スレッドから行なっていたりしますか？

もしそうなら、この例外は起こると思います。

**Comment by kenichi-kobayashi** [comment]
返信ありがとうございます。

allItemsに、Addするインスタンスが1000個ほどあります。
allItemsにAddする際は、UIスレッドで順列実行していますが、
そこにAddするためのインスタンス生成は、高速化のためAsParallel()で並列実行しています。
これにより実行時間が１／５程度に高速化させることができましたので、ここは保持したいです。

インスタンスを並列実行していることで、ToFilteredで観測している「IsChecked.Value」は、UIスレッド以外で生成されたRPSlimとなっています。
runceelさんのコメントを見て気づきましたが、RPSlimnのインスタンス生成がUIスレッドではないのでここが問題でしょうか？
であれば、IsCheckedをPOCOプロパティに移行してみたいと思います。

ちなみに、RPSlimnのインスタンス生成は、UIスレッド以外ですが、.Valueを更新するのはUIスレッドから行われています。
ちなみに、ちなみに、ToFilteredでは、IsChecked.Valueの変更を観測できないので、以下のような細工をしていましたので、この細工もなくなってすきっりします。

```cs
IsChecked.Skip(1).Subscribe(_ => this.RaisePropertyChanged(nameof(IsChecked))); 
```

お考えを聞かせていただけるとありがたいです。

**Comment by runceel** [comment]
@kenichi-kobayashi さん

実際に一度でもいいので手元で発生させたいと思っているのですが、実際にエラーが発生したことのある実績のあるコードベースはどこかで参照可能でしょうか？？
闇雲に手を入れるよりは、もう少しあたりをつけて直したいと思っているので可能であればお願いします。

`ReactivePropertySlim<T>` は、イベントの発生するスレッドの自動ディスパッチは行わないので特に関係は無いと思います。

おそらくなのですが @kenichi-kobayashi さんがエラーの発生には関係ないだろうと省いてる部分のコードにある処理が ReactiveProperty のライブラリのコード内の何らかの処理と相性が悪い（もしくは ReactiveProperty のバグ) に当たってるのだと思うのですが、今のままだととりあえず怪しいのでロックしてみるくらいしか手のうちようがなくて、なるべくそういう形での修正は避けたいと考えています。

**Comment by kenichi-kobayashi** [comment]
返信ありがとうございます。

＞実際にエラーが発生したことのある実績のあるコードベースはどこかで参照可能でしょうか？？
ビジネスロジックがはいってしまっているので、そのまま提供することは難しそうです。
なので、サンプルプログラムを実装しようとしているのですが、やはり簡単に再現しないので、サンプルプログラムの提供も、時間がかかってしまいそうです。(影響ないとおもっているところが影響あると、お手上げですね。。）

うーん。。どうするべきか。
例えば、ログを強化版のRPパッケージを提供してもらうことはできませんか？

そしたら、こちらの再現した実績があるコードで、ひたすら再現テストを実施して、ログを取得するような手はずで進められます。

いかがでしょうか？

**Comment by runceel** [comment]
ReactiveProperty なら clone して ReactiveProperty のプロジェクトを開いて Core, NetStandard, WPF , Shared のプロジェクト以外はアンロードしてビルドすると bin フォルダーの下の  Debug に NuGet パッケージまでまとめて作られると思うのでそこにログなど足してもらうことが出来ると思います。

**Comment by runceel** [comment]
内部のコレクションを操作するところを lock するようにしたものをリリースしてみました。

https://www.nuget.org/packages/ReactiveProperty/8.0.0-pre202109160117

**Comment by kenichi-kobayashi** [comment]
返信が遅くなりましたが、状況を報告させてください。

リリースしてもらったパッケージで、ひたすら再現テストを実施しましたが、現象が発生しないことから、問題が解決した模様です。

本対応においては、本流に取りこんでもらってよさそうに思います。

今回も、スピーディな対応を実施していただき、本当に助かりました。

今後とも、なにとぞ、よろしくお願いいたします。

**Comment by runceel** [comment]
@kenichi-kobayashi 
11 月に .NET 6 が出たタイミングで 8.0 を正式にするので、それまで現状のパッケージをご利用ください。
