### ISSUE TITLE
Update Reactive Extensions dependencies

### ISSUE THREAD

**Issue by ApocalypticOctopus** [runceel/ReactiveProperty#29]
Reactive Extensions changed their package names when they moved to the .NET Foundation, and then the unlisted all the old packages. This means that it's easy to wind up with the new packages *and* the old packages of Reactive Extensions installed when depending on both System.Reactive and on ReactiveProperty.

Here are the steps to reproduce:

1. In Visual Studio, create a new console project
2. Add a NuGet dependency on [System.Reactive](https://www.nuget.org/packages/System.Reactive/)
3. Add a NuGet dependency on Reactive Property
4. You now have System.Reactive *and* Rx-Main style packages in your list of project references. This means that you have duplicate DLLs with identical namespaces and classes and everything.

Read more about it [here](https://github.com/Reactive-Extensions/Rx.NET/releases/tag/v3.0.0).

The new Reactive Extensions is source compatible, so switching out the packages should not break anything.

**Comment by runceel** [comment]
Thank you for your feedback.

We started to update at vNext branch!
Please wait a moment.

**Comment by runceel** [comment]
We can't release ReactiveProperty of System.Reactive 3.0.0 version.
Because System.Reactive is having this issue.
https://github.com/Reactive-Extensions/Rx.NET/issues/216

If your platform is .NET 4.x then try ReactiveProperty 3.0.0-pre1 package.

**Comment by ApocalypticOctopus** [comment]
Thank you for your effort! We'll use a workaround for now.
