### ISSUE TITLE
Missing Method exception on Xamarin.Android

### ISSUE THREAD

**Issue by viniciusmelquiades** [runceel/ReactiveProperty#30]
I got the following exception when trying to run `Reactive.Bindings.Helpers.FilteredReadOnlyObservableCollection.ToReadOnlyReactiveCollection` either by invoking it or by using the extension method.

```
System.Reflection.TargetInvocationException: Exception has been thrown by the target of an invocation. ---> System.MissingMethodException: Method 'FilteredReadOnlyObservableCollection.ToReadOnlyReactiveCollection' not found.
```

The code is in a PCL, and I'm trying to run it on Xamarin.Android

**Comment by runceel** [comment]
I could run this code.

```cs
using Reactive.Bindings.Helpers;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.ComponentModel;
using System.Linq;
using Xamarin.Forms;

namespace App44
{
    public class App : Application
    {
        public App()
        {
            // The root page of your application
            var myContext = new MyContext();
            MainPage = new ContentPage
            {
                Content = new StackLayout
                {
                    VerticalOptions = LayoutOptions.StartAndExpand,
                    Children = {
                        new ListView {
                            ItemsSource = myContext.People
                        }
                    }
                }
            };
        }

        protected override void OnStart()
        {
            // Handle when your app starts
        }

        protected override void OnSleep()
        {
            // Handle when your app sleeps
        }

        protected override void OnResume()
        {
            // Handle when your app resumes
        }
    }

    public class Person : INotifyPropertyChanged
    {
        public string Name { get; set; }

        public override string ToString() => this.Name;

        public event PropertyChangedEventHandler PropertyChanged;
    }

    public class MyContext
    {
        public IEnumerable<Person> People { get; }

        public MyContext()
        {
            var coll = new ObservableCollection<Person>(Enumerable.Range(1, 10)
                .Select(x => new Person { Name = $"tanaka {x}" }));
            this.People = coll.ToFilteredReadOnlyObservableCollection(x => x.Name.Contains("1"));
        }
    }
}
```
My step is
- Create Xamarin.Forms project.
- Add ReactiveProperty reference from NuGet.
- Write App.cs
- Update Xamarin.Forms
- Run android application.

**Comment by viniciusmelquiades** [comment]
As I said, the error happens when I try to call the method `ToReadOnlyReactiveCollection` on the result of the `ToFilteredReadOnlyObservableCollection`. I already found another way to do what I wanted. I'm not even sure it was possible to do what I wanted with this library

**Comment by runceel** [comment]
Oh, sorry. I was misread!

But, I have can run this program.

```cs
using Reactive.Bindings.Helpers;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.ComponentModel;
using System.Linq;
using Xamarin.Forms;

namespace App44
{
    public class App : Application
    {
        public App()
        {
            // The root page of your application
            var myContext = new MyContext();
            MainPage = new ContentPage
            {
                Content = new StackLayout
                {
                    VerticalOptions = LayoutOptions.StartAndExpand,
                    Children = {
                        new ListView {
                            ItemsSource = myContext.People
                        }
                    }
                }
            };
        }
    }

    public class Person : INotifyPropertyChanged
    {
        public string Name { get; set; }

        public override string ToString() => this.Name;

        public event PropertyChangedEventHandler PropertyChanged;
    }

    public class MyContext
    {
        public IEnumerable<Person> People { get; }

        public MyContext()
        {
            var coll = new ObservableCollection<Person>(Enumerable.Range(1, 10)
                .Select(x => new Person { Name = $"tanaka {x}" }));
            // Here!!
            this.People = coll.ToFilteredReadOnlyObservableCollection(x => x.Name.Contains("1"))
                .ToReadOnlyReactiveCollection();
        }
    }
}
```

I am still misread??

**Comment by viniciusmelquiades** [comment]
Sorry for the delay. My debugger threw this exception at my face when I tried running your code.

```
System.MissingMethodException: Method 'FilteredReadOnlyObservableCollection.ToReadOnlyReactiveCollection' not found.
```

This is exactly the problem I had. I'm using the most updated version of Xamarin.Android

**Comment by runceel** [comment]
I'm using stable channel Xamarin.Android on Visual Studio 2015 Update 3.
What are you using?

**Comment by viniciusmelquiades** [comment]
I'm using Visual Studio 2015 Update 3 too, but I think I'm on the alpha channel of Xamarin (form when I tried using the Xamarin.Forms designer). I'll revert back to the stable channel and let you know the results.

**Comment by runceel** [comment]
I have found that case MissingMethodException.

ProjectA(Xamarin.Android) referenced ReactiveProperty v2.7.x and ProjectB(PCL) referenced ReactiveProperty v2.8.0.

I added ToReadOnlyReactiveProperty method arguments on ReactiveProperty v2.8.0.

How is your project setting?

**Comment by viniciusmelquiades** [comment]
Only my Portable project references ReactiveProperty v2.8.0. The Android Project has no direct reference to ReactiveProperty.

I decided to downgrade the ReactiveProperty to version 2.7.4, to test it, and used your code, and it worked. The problem seems to be with version 2.8.0

**Comment by runceel** [comment]
I have removed references ReactiveProperty v2.8.0 from App44.Droid project.But It could run.

Could you try to remove bin/obj folder and rebuild?(use ReactiveProperty v2.8.0)

**Comment by viniciusmelquiades** [comment]
Sorry it took me this long to answer.

Removing the bin/obj folders seem to have worked. I thought rebuilding the solutions would do that for me. Sorry to bother you. Though it would be nice to have this issue in some sort of FAQ, in case someone else have this problem.

**Comment by runceel** [comment]
Problem, we were glad seemed to solve.
