### ISSUE TITLE
validation limitations?

### ISSUE THREAD

**Issue by jmagaram** [runceel/ReactiveProperty#31]
I'm wondering if there are some limitations in data validation. (A) While validation is happening, it is helpful to display a message letting the user know that an operation is in progress. Users may want to know if a long validation process ends in (B) error/exception or is (C) canceled so they can try again. Finally, (D) if validation is slower than the generation of values to validate, I think your code might notify listeners that error information has been updated, but the information that is published via INotifyDataErrorInfo may pertain to an older version of the property. All this makes me wonder if the validation function that is passed in to ReactiveProperty should work like this...
```cs
public enum ValidationProgress { Running, Completed, Faulted, Canceled }

public interface IValidationErrorInfo<T> {
    T Value { get; }
    ValidationProgress Progress { get; }
    IEnumerable Errors { get; }
    bool? HasErrors { get; }
    Exception Exception { get; }
}

public delegate IObservable<IValidationErrorInfo<T>> Validator<T>(IObservable<T> values);
```
In IValidationErrorInfo<T>, HasErrors and Exception would be null if the progress is Running, Faulted, or Completed. You could automatically determine if ValidationProgress is Running - rather than relying on the validator function - as follows...
```cs
var latestValidationResults = Observable
    .CombineLatest(valuesToValidate, validator(valuesToValidate), 
        (v, r) => new { Value = v, Results = r });
var isValidating = latestValidationResults.Select(i => !Equals(i.Results.Value, i.Value));
```
Notice how this expression tests whether the validation results for a particular value match the current value stored in the property? This prevents you from publishing stale data. I would expect a ReactiveProperty instance to have a public member like what is shown below so other properties/code in your classes can inspect the current validation state.
```cs
IReadOnlyReactiveProperty<IValidationErrorInfo<T>> ValidationErrors { get; }
```

 A similar expression would give you the most recent and relevant validation information to publish via INotifyDataErrorInfo. I'm not sure exactly how to map between IValidationErrorInfo<T> and INotifyDataErrorInfo. Maybe you assume that if ValidationProgress is Canceled, Faulted, or Running, that HasErrors is true.

**Comment by jmagaram** [comment]
If you wanted to provide cancellation support within the ReactiveProperty, users of ReactiveProperty could provide one of these...
```cs
public interface IValidationService<T> {
    void TryCancel();
    IObservable<IValidationErrorInfo<T>> Validate(IObservable<T> values);
}
```
And then expose a TryCancelValidation() method on the ReactiveProperty itself.

**Comment by jmagaram** [comment]
One more possibility is to have the validation service return a Task since Tasks already support knowing whether the operation was canceled or faulted. Something like this...
```cs
public interface IValidationErrors {
    IEnumerable Errors { get; }
    bool HasErrors { get; }
}

public interface IValidationService<T> {
    // Attempt to cancel validation on the specific value.
    void TryCancel(T value);

    // Attempt to cancel validation on the latest value.
    void TryCancel();

    // AsyncState on the Task MUST be set to the value being validated
    IObservable<Task<IValidationErrors>> Validate(IObservable<T> values);
}

var latestValidationResults = Observable
    .CombineLatest(values, validationService.Validate(values),
        (v, t) => new { Value = v, ValidationTask = t })
    .Where(i => ((int)i.ValidationTask.AsyncState) == i.Value)
    .Select(async i => await i.ValidationTask);

```

**Comment by runceel** [comment]
Thank you for your feedback.
But sorry, my first language is Japanese. I can't understand your all message.

If you want to get IsValidating and LatestValidationResult then I provide this sample code.

```cs
using Reactive.Bindings;
using System;
using System.Linq;
using System.Reactive.Linq;
using System.Threading.Tasks;

namespace ConsoleApplication1
{
    class Program
    {
        static void Main(string[] args)
        {
            var r = new ReactiveProperty<int>()
                .SetValidateNotifyError(async x =>
                {
                    await Task.Delay(x * 1000);
                    return x % 2 == 0 ? $"invalid {x}" : null;
                });

            Observable.Merge(
                r.Select(_ => 1),
                r.ObserveErrorChanged.Select(_ => -1))
                .Scan((x, y) => x + y)
                .Select(x => x != 0)
                .Subscribe(x => Console.WriteLine($"IsValidating: {x}"));

            r.ObserveErrorChanged
                .Select(x => x?.OfType<string>()?.FirstOrDefault())
                .Subscribe(x => Console.WriteLine($"Latest validation result: {x}"));

            r.Value = 10; // invalid
            r.Value = 1; // valid
            r.Value = 2; // invalid
            Console.ReadKey();
        }
    }
}
```

Cancel is difficult...

Thank you.

**Comment by jmagaram** [comment]
That does not always work.

r.Throttle(Timespan.FromSeconds(2)).Count()!=r.ObserveErrorChanged.Count()

**Comment by runceel** [comment]
Why throttle??
