### ISSUE TITLE
ReadOnlyReactiveCollection.ToCollectionChanged() を購読し CollectionChanged.Value を参照すると InvalidCastException が発生する

### ISSUE THREAD

**Issue by isonzo-3171** [runceel/ReactiveProperty#316]
`ReadOnlyReactiveCollection.ToCollectionChanged().Subscribe()` に渡すラムダ式内で `CollectionChanged.Value` を参照すると，ラムダ式の当該箇所が実行された際に `InvalidCastException` が発生します．以下のコードで再現できます．この現象はバージョン 8.0.0 で発生します．7.12.0 では発生しません．
```C#
var source = new ReactiveCollection<string>();
var readOnly = source.ToReadOnlyReactiveCollection();

readOnly.ToCollectionChanged().Subscribe(x => Console.WriteLine($"{x.Value}"));

source.Add("abc");
// System.InvalidCastException: 'Unable to cast object of type 'SelectEnumerableIterator`2[System.String,System.String]' to type 'System.String'.'
```
例外メッセージによれば，この例外が発生したとき `CollectionChanged.Values` の最初の要素に ```SelectEnumerableIterator`2[System.String,System.String]``` が入っているそうです．しかし本当なら `string` が入っているはずです．
どうやって `CollectionChanged.Values` の要素にイテレータが入ったかというと，`ReadOnlyReactiveCollection` のコンストラクタ内でいろいろ購読しているあたりの [`return new (NotifyCollectionChangedAction.Add, args.Values, args.Index); `](https://github.com/runceel/ReactiveProperty/blob/2a659254878e6b71e6e33bdcfa520f5fb9c6b1f6/Source/ReactiveProperty.NETStandard/ReadOnlyReactiveCollection.cs#L53) の部分で `NotifyCollectionChangedEventArgs` のコンストラクタのうち `NotifyCollectionChangedEventArgs(NotifyCollectionChangedAction action, object changedItem, int index)` が呼ばれているからではないかと思われます．
```C#
subject.Where(x => x.Action == NotifyCollectionChangedAction.Add)
    .Subscribe(x => ApplyCollectionChanged(x, static (source, args) =>
    {
        var index = args.Index;
        foreach (var item in args.Values)
        {
            source.Insert(index++, item);
        }

        return new (NotifyCollectionChangedAction.Add, args.Values, args.Index);  // <=ここ
    }))
    .AddTo(Token);
```
`IEnumerable<T>` である `args.Values` をコンストラクタに渡しているところを見るに複数要素の変更を知らせたかったのではないかと思いますので，`NotifyCollectionChangedEventArgs(NotifyCollectionChangedAction action, IList changedItems, int startingIndex)` 等の引数に`IList` を受け入れるコンストラクタの呼び出しを意図していたのではないでしょうか．試しに `return new (NotifyCollectionChangedAction.Add, args.Values.ToArray(), args.Index);` としたところ例外は発生しなくなりました．

よくわからないことを言っているかもしれませんがご確認の程よろしくお願いいたします．

**Comment by runceel** [comment]
こちらの問題に対応した v8.0.1 のプレビュー版をリリースしました。

**Comment by isonzo-3171** [comment]
お忙しい中ご確認いただきありがとうございます．`8.0.1-pre202111200140` に差し替えてみたところ表題の現象は発生しなくなりました．

**Comment by runceel** [comment]
ありがとうございます。
v8.0.1 の正式版のリリースのワークフローを実行したので暫くしたら正式版が NuGet 上で使えるようになると思います。

一旦このIssueは閉じますが、何かあったらコメント等で教えてください。
