### ISSUE TITLE
ToReadOnlyRactiveCollectionがデータを二重に処理してしまう

### ISSUE THREAD

**Issue by yoshimur** [runceel/ReactiveProperty#322]
以下のようなコードを記載してから、listにデータをaddした場合に、rListには、二重にデータが登録される場合がある。
8.0.2で発生、7.12.0では発生していなかった。
VS2019使用。
```
list = new ObservableCollection<Foo>();
rlist = list.ToReadOnlyReactiveCollection(x => new FooViewModel(x));
```

**Comment by runceel** [comment]
@yoshimur 利用しているプラットフォーム（.NET のバージョン）や、Schedulerなどなにか設定していたり等ありますか？

**Comment by runceel** [comment]
以下のようなプログラムを暫く実行し続けていたのですが、簡単には事象が確認できませんでした。

```csharp
using Reactive.Bindings;
using System.Collections.ObjectModel;

while(true)
{
    var list = new ObservableCollection<Foo>();
    var rlist = list.ToReadOnlyReactiveCollection(x => new FooVM(x));

    for (var i = 0; i < 1000; i++)
    {
        list.Add(new Foo());
    }

    Console.WriteLine(list.Count);
    Console.WriteLine(rlist.Count);
    if (list.Count != rlist.Count) throw new InvalidOperationException();
}

record Foo();
record FooVM(Foo Foo);
```

**Comment by yoshimur** [comment]
.netのバージョンは、5.0、VS2019です。
また、list.Addしたメソッドから、抜けたところで、rListのラムダ式が実行されて
その時に、二重にループが発生していました。
特にスケジューラ等は設定していません。

こんなイメージです。

```
private void setup(){
    var list = new ObservableCollection<Foo>();
    var rlist = list.ToReadOnlyReactiveCollection(x => new FooVM(x));

    for (var i = 0; i < 1000; i++)
    {
        list.Add(new Foo());
    }
}

```
このメソッドから抜けた時点で、rListのnew FooVM()が実行されて、その結果、ループがダブルで回っていました。

**Comment by runceel** [comment]
@yoshimur ありがとうございます。
再現度合いは特定の手順を踏むと必ず起きる感じですか？

もし可能でしたら再現プロジェクトとか準備していただくことは可能ですか？

**Comment by yoshimur** [comment]
こちらのプロジェクトが再現プロジェクトになります。
VS2019、.net5.0で作成したプロジェクトになります。

[Sample.zip](https://github.com/runceel/ReactiveProperty/files/7642860/Sample.zip)

**Comment by soi013** [comment]
横からすいません。
"Sample.zip"のプロジェクトはこちらの環境では再現します。

いくつかいじってみると、以下の条件のときに発生するようです。

- `list.Clear()`の後に連続して`list.Add(...)`する。
- `Synchronizationcontext`が有効な状態で、schedulerに`ReactivePropertyScheduler.Default`などを指定する。

回避策としては以下があります。

- `list.Clear()`と`list.Add(...)`の間に`await Task.Delay()`をいれる
- schedulerに`Scheduler.Immediate`を指定する

おそらくですが、原因はReset時に以下の部分で再度追加されてしまっているのではないでしょうか？

https://github.com/soi013/ReactiveProperty/blob/0f8ce8603aeba79c427548a637778d7712616b2e/Source/ReactiveProperty.NETStandard/ReadOnlyReactiveCollection.cs#L167

**Comment by runceel** [comment]
ありがとうございます。
これだけ再現するのであれば直せそうです。

**Comment by runceel** [comment]
@yoshimur こちらでも再現しました。根本的な問題の対処にはなりませんがコレクションの操作を UI スレッド上から行っている場合は NuGet から ReactiveProperty ではなく ReactiveProperty.WPF のパッケージを追加していただいて、App クラスの Startup イベントハンドラで WPF 用のスケジューラーを設定していただくことで現時点でも回避可能です。

```
using Reactive.Bindings;
using Reactive.Bindings.Schedulers;
using System.Windows;

namespace Sample
{
    /// <summary>
    /// Interaction logic for App.xaml
    /// </summary>
    public partial class App : Application
    {
        private void Application_Startup(object sender, StartupEventArgs e)
        {
            ReactivePropertyScheduler.SetDefault(new ReactivePropertyWpfScheduler(Dispatcher));
        }
    }
}
```

@soi013 さん
いつもありがとうございます。ご指摘の通りその場所だと思います。Clear 以外の Reset に対応したことによって発生してしまった不具合ですね…。

**Comment by runceel** [comment]
@yoshimur さん
v8.0.3 のプレビュー版を公開しました。

**Comment by yoshimur** [comment]
@runceel さん
ありがとうございます。確認いたします。

**Comment by runceel** [comment]
@yoshimur さん
単体テストで再現テストを作って確認した範囲ではOKでしたが、頂いていた再現プロジェクトに修正版を入れてみたらダメでした orz

もうちょっと処理を見直します。すいません。

**Comment by yoshimur** [comment]
プレビュー版で問題ないことを確認いたしました。
ありがとうございます。

**Comment by soi013** [comment]
部分的に直るみたいです。最初に実行するところでは直って、2回目以降では再現します。

2重にならない

```csharp
private void Setup()
{
    list.Clear();
    list.Add("first");
    list.Add("second");
}
```


2重になる

```csharp
UpdateComboCommand.Subscribe(() =>
    {
        list.Clear();
        list.Add("Part1");
        list.Add("Part2");
    });
```

**Comment by runceel** [comment]
2 重になる部分もコレクション内の要素数は 2 なのに UI 上は 4 個表示されてますね。

**Comment by runceel** [comment]
もうちょっと調べてみたら ComboBox は 4 個表示されて、ListBoxにバインドするとちゃんと2個になりますね…

**Comment by soi013** [comment]
そうですね。
ObservableCollection(`list`)もReadOnlyReactiveCollection`ComboList`も2個ですが、Comboboxは4個になるようですね。
Bindingの問題ですかね

**Comment by runceel** [comment]
ちょっと処理をする実行スレッドを変えたものをNuGetにリリース中です

**Comment by soi013** [comment]
私の環境では直りました。

**Comment by runceel** [comment]
@yoshimur @soi013 
v8.0.3 をリリースしました。
