### ISSUE TITLE
Upgrade to latest Rx?

### ISSUE THREAD

**Issue by BryantL** [runceel/ReactiveProperty#33]
Reactive Extensions has changed package ids and strong name (documented here https://github.com/Reactive-Extensions/Rx.NET).

Is ReactiveProperty going to be upgraded to the latest version (perhaps as a 3.0 branch?)?

Thanks,
Bryant

**Comment by runceel** [comment]
Thank you for your feedback.

We are working on vNext branch.And released 3.0.0-pre package.

But we had issue on Xamarin. That is compile error when added Rx3.0 on Xamarin.Android.

**Comment by BryantL** [comment]
Thanks for the info.

Apologies that I didn't spot the pre-release nuget packages
