### ISSUE TITLE
Insall error in Xamarin project

### ISSUE THREAD

**Issue by saipan810** [runceel/ReactiveProperty#34]
Xamarinプロジェクト(PCLプロジェクト)でver3.0.0 インストール時に下記エラーが発生しています。
ver2.9.0では問題ありません。

> パッケージ 'System.ComponentModel.Annotations.4.1.0 : System.Runtime [4.1.0, )' はプロジェクト 'TestProject' に存在しません

プロジェクトは下記で作成したものです。
NewProject -> Visual C# -> Cross-Platform
Blank Xaml App (Xamarin.Forms.Portable)

**Comment by runceel** [comment]
Xamarin.Formsで使う場合は以下の手順を踏む必要があります。
それでもダメでしょうか？

https://github.com/runceel/ReactiveProperty/blob/master/HowToUseXF-ja.md

**Comment by runceel** [comment]
早速3.0を使っていただいてありがとうございます。
また、何かあったらよろしくお願いします。
