### ISSUE TITLE
Collection update

### ISSUE THREAD

**Issue by FoxTes** [runceel/ReactiveProperty#342]
Hello. A question about the work of collections.
I have previously used RX UI.

Every time the NavigationSearchText changes, I have to get a new collection, but in my case I get the old collection plus the new one (adding element). I used a crutch like (.Do (_ => NavigationSearchItems? .ClearOnScheduler ())).

```
            NavigationSearchItems = NavigationSearchText
                .Skip(1)
                .Throttle(TimeSpan.FromMilliseconds(500))
                .Select(term => term?.Trim())
                .DistinctUntilChanged()
                .Do(_ => NavigationSearchItems?.ClearOnScheduler())
                .SelectMany(x => nameMenuItems.Where(y => y.Contains(x, StringComparison.OrdinalIgnoreCase)))
                .ToReactiveCollection();
```

Please, tell me how to do it better.

**Comment by soi013** [comment]
Probably, change this.

```

.ToReactiveCollection();

👇

.ToReadOnlyReactivePropertySlim();

```

**Comment by FoxTes** [comment]
> 

This change does not work. The logic of work is changing.

**Comment by soi013** [comment]
OK, how about this.
`NavigationSearchItems` type is changed.

```csharp
NavigationSearchItems = NavigationSearchText
                .Skip(1)
                .Throttle(TimeSpan.FromMilliseconds(500))
                .Select(term => term?.Trim())
                .DistinctUntilChanged()
                .Select(x => nameMenuItems
                   .Where(y => y.Contains(x, StringComparison.OrdinalIgnoreCase))
                   .ToArray())
                .ToReadOnlyReactivePropertySlim();
```

**Comment by FoxTes** [comment]
Yes. It works. Thanks for the help.

But still. Better why does the collection have this behavior? Is it better to use properties or a collection in this case?

**Comment by runceel** [comment]
@FoxTes
I guess it works replacing to `Clear()` from `ClearOnScheduler()` and adding `ObserveOnUIScheduler()` after `DistinctUntilChanged()`.

```csharp
NavigationSearchItems = NavigationSearchText
                .Skip(1)
                .Throttle(TimeSpan.FromMilliseconds(500))
                .Select(term => term?.Trim())
                .DistinctUntilChanged()
                .ObserveOnUIDispatcher()
                .Do(_ => NavigationSearchItems?.Clear())
                .SelectMany(x => nameMenuItems.Where(y => y.Contains(x, StringComparison.OrdinalIgnoreCase)))
                .ToReactiveCollection();
```

However, I recommend @soi013 's approach. Because you said "Every time the NavigationSearchText changes, I have to get a new collection,", I guess it means `ReadOnlyReactiveProperty<string[]>`.

**Comment by FoxTes** [comment]
Thanks for the explanation. I will take this into account in the future.
