### ISSUE TITLE
BusyNotifier でも Await したい

### ISSUE THREAD

**Issue by kenichi-kobayashi** [runceel/ReactiveProperty#347]
いつも大変、お世話になっています。

BusyNotifier で Await できないのですが、これは仕様でしょうか？
ユースケースとしては、結構、使いたい場合があるので、対応してもらえるとありがたいです。

例えば、実行ボタンとキャンセルボタンの2つ用意して、キャンセルボタン押下時は、キャンセル完了を待ちたい場合があります。
現状、BusyNotifier ではawaitができないので、一旦、RPSなどに変換して、Awaitしています。

```
public class MainWindowViewModel
    {
        public AsyncReactiveCommand ExecCommand { get; set; }
        public AsyncReactiveCommand CancelCommand { get; set; }
        public BusyNotifier IsBusy { get; set; }

        public MainWindowViewModel()
        {
            IsBusy = new BusyNotifier();
            ExecCommand = IsBusy.Select(a => !a).ToAsyncReactiveCommand().WithSubscribe(async () =>
            {
                using (IsBusy.ProcessStart())
                {
                    await Task.Run(() => System.Threading.Thread.Sleep(5000));
                }
            });

            CancelCommand = IsBusy.ToAsyncReactiveCommand().WithSubscribe(async () =>
            {
                if (IsBusy.IsBusy)
                    // await IsBusy; // ×正しく動作しない。これを使いたい。
                    await IsBusy.ToReadOnlyReactivePropertySlim();  //〇正しく動作する
                    // await IsBusy.ToReadOnlyReactivePropertySlim().Where(a => !a); //×正しく動作しない

                MessageBox.Show("Canceled!");
            });
        }
    }
```

いかがでしょうか？

[AwaitReactiveTest.zip](https://github.com/runceel/ReactiveProperty/files/8054899/AwaitReactiveTest.zip)

**Comment by runceel** [comment]
BusyNotifier の async/await の挙動は IObservable に対する async/await の挙動になります。
これは OnCompleted が発火したら返ってくる挙動になります。

ReactiveProperty は今特別に対応して今の挙動にしている感じです。
悩ましいところですね…

**Comment by kenichi-kobayashi** [comment]
返信ありがとうございます。

なるほど。

IO仕様に合わせているわけですね。

であれば、RPSに変換してawaitするのが良いと言うことですね。

であれば、その仕様で進めようと思います。

本件、仕様と言うことであれば、クローズさせていただきます。

**Comment by runceel** [comment]
`IO` の仕様に合わせてるというよりは `BusyNotifier` は `IObservable<bool>` を実装しているので何もしないとそうなります。
`ReactiveProperty` だけが特別に対応しているといったような形です。

現状は仕様です。

**Comment by kenichi-kobayashi** [comment]
回答ありがとうございます。了解しました。
ToReactiveProperty()を実行して、awaitしていこうと思います。
