### ISSUE TITLE
Model層のItemsをViewModel層のItemsに同期する方法

### ISSUE THREAD

**Issue by kenichi-kobayashi** [runceel/ReactiveProperty#350]
いつも大変、お世話になっています。

MVVMを実施しているとよくあるのが、以下のようなModel層のPlayersを、DataGridなどの画面に出したい場合があります。

    public class TeamModel : Bases.ModelBase
    {
        public ObservableCollection<PlayerModel> Players { get; set; } = new ObservableCollection<PlayerModel>();
    }

この場合、ViewModel層としては、以下のようにしています。

    public class TeamViewModel : Bases.ViewModelBase
    {
        public ObservableCollection<PlayerViewModel> Players { get; set; }

        public TeamViewModel(Models.TeamModel model)
        {
            Players = new ObservableCollection<PlayerViewModel>(model.Players.Select(a => new PlayerViewModel(a)));
            Players.ObserveAddChanged().Subscribe(a => model.Players.Add(a.Model)).AddTo(disposables);
            Players.ObserveRemoveChanged().Subscribe(a => model.Players.Remove(a.Model)).AddTo(disposables);
        }
    }

ReactiveCollectionなどを使うと、もう少しスマートな実装ができるような気がして、色々と調べてみたのですが、特に、これといったものを探すことができませんでした。

みなさん、こんな感じで実装しているのでしょうか？
何かもっと、良い方法があれば、ご教授願えれば幸いです。

参考までに、以下にプロジェクトを配置しておきます。
https://github.com/kenichi-kobayashi/WpfApp1

**Comment by runceel** [comment]
ViewModel 側がリードオンリーでいいなら、このように書くことが出来ます。

```csharp
public class TeamViewModel : Bases.ViewModelBase
{
    public ReadOnlyReactiveCollection<PlayerViewModel> Players { get; }

    public TeamViewModel(Models.TeamModel model)
    {
        Players = model.Players
            .ToReadOnlyReactiveCollection(x => new PlayerViewModel(x))
            .AddTo(disposables);
    }
}
```

**Comment by kenichi-kobayashi** [comment]
返信ありがとうございます。

ReadOnlyであれば、その通りですね。

ReadOnlyじゃないとするならば、現状は、前述の記載の通りにするのが、よさそうですかね？

AsSynchronizedのようなReactiveCollectionがあって良い気がしていますが、いかがでしょうか？

**Comment by runceel** [comment]
双方向同期は実装難しそうですね…。
作り的にも Model の方に更新かけて、それを VM に反映するという流れにした方が良いと思うので、一方通行の方がいいと思います。

**Comment by runceel** [comment]
@kenichi-kobayashi 

> ReadOnlyじゃないとするならば、現状は、前述の記載の通りにするのが、よさそうですかね？

この部分ですが、Add と Remove だけに対応するならそれで大丈夫だと思います。
その他にも VM のプロパティが変更された場合や、コレクションの要素の入れ替えや、クリアされたときなどアプリケーションで想定されるケースに対応した同期ロジックを書く必要があると思います。

**Comment by runceel** [comment]
一旦クローズします。何かあればコメント、再オープンお願いします。
