### ISSUE TITLE
ReadOnlyReactiveCollection の変更通知情報が正しくない場合がある

### ISSUE THREAD

**Issue by toras9000** [runceel/ReactiveProperty#354]
おそらく設計意図通りではないと思われる挙動に遭遇しましたので、報告いたします。
ReadOnlyReactiveCollection にて、CollectionChanged で通知されるイベント引数の内容が正しくない場合があるようです。

以下、調査してみた見解となります。
ReactiveProperty 8.0.3 の実装にて IObservable&lt;T&gt; を受け取る ReadOnlyReactiveCollection のコンストラクタオーバロード内に以下のような実装個所があります。

```
ox.Select(x => CollectionChanged<T>.Add(_source.Count, x))
            .ObserveOn(_scheduler)
            .Subscribe(x => ApplyCollectionChanged(x, static (source, args, _) =>
・・・・
```

上記の `CollectionChanged<T>.Add()` で情報を作成する箇所にて`_source.Count` を参照していますが、その個所はソースとなるObservableシーケンスの実行コンテキストであるため、そこで値を取得すると正しい値を得られない場合があるかと思います。
実際に `_source` に値を追加するのはスケジューラのコンテキスト上であり、それが処理される前にシーケンスに次の要素が来た場合には `Count` の値は通知すべき Index 値にならないかと思います。

一応、上述に記載の状態を試す目的のサンプルを以下に用意しました。
もし必要がありましたら参照ください。
https://github.com/toras9000/TestRxpCollection

**Comment by runceel** [comment]
@toras9000 
ありがとうございます。修正してみた v8.0.4-pre202203040658  をリリースしました。

https://www.nuget.org/packages/ReactiveProperty/8.0.4-pre202203040658

このパッケージを使うと提供して頂いたサンプルも以下のような結果になります。

![image](https://user-images.githubusercontent.com/79868/156729489-35f60e8e-3d57-4b51-aa37-daf0e1204b79.png)

**Comment by toras9000** [comment]
ご対応ありがとうございます。
v8.0.4-pre202203040658 にて修正されることを当方でも確認いたしました。

また参考までにですが、この事象はWPF で  ReadOnlyReactiveCollection をUIにバインドしていた際、フレームワークから「指定されたインデックス '0' で、追加された項目が表示されません。」というエラーが生じたことで見つけたのですが、それが解消されることも確認できました。

**Comment by runceel** [comment]
v8.0.4をリリースしました。
報告ありがとうございました。
