### ISSUE TITLE
複数ウィンドウでReactivePropertyを使うとスレッドの例外が発生する

### ISSUE THREAD

**Issue by MaxfieldWalker** [runceel/ReactiveProperty#36]
いつもお世話になっております。
ReactivePropertyについて一つ質問があります。

UWPでワードやエクセルや付箋のように，全く同じウィンドウを複数開くことのできるアプリを作っているのですが，2つ目以降のウィンドウでモデルのプロパティに変化が生じると`The application called an interface that was marshalled for a different thread.`というお決まりの例外が発生してしまいます。

![image](https://cloud.githubusercontent.com/assets/7913793/19192664/f0ee252c-8ce1-11e6-8d5a-74502d2ca045.png)

対策としてスケジューラに`SynchronizationContextScheduler`を指定してみたら例外が発生しなくなりました。ですが，そもそもRxのスケジューラをよく分かっていないのでこれが正しい対処なのかも判断がつきません。また，仮にスケジューラが正しいとしても全てのプロパティにスケジューラを設定するのはおかしな感じがします。

```csharp
this.Title = new ReactiveProperty<string>(
    raiseEventScheduler: new SynchronizationContextScheduler(SynchronizationContext.Current),
    initialValue: "");
```

再現プロジェクトを添付しますので，もしよければ見てやってください。

2つ目以降のウィンドウはタスクバーでアプリのアイコンを中クリックするなどで開いてください。

[MultiWindowApp-master.zip](https://github.com/runceel/ReactiveProperty/files/516371/MultiWindowApp-master.zip)

環境
- Windows 10 1067
- Visual Studio 2015
- Prism.Unity
- ReactiveProperty

**Comment by runceel** [comment]
ReactivePropertyが、UIスレッドが1つであることを前提に作られてることが原因になります。
なので、この動きは仕様で、UWPでWindowを複数表示するとき（UIスレッドがWindowごとにできる）は、やられてる対処で正しいです。

なんとかしたいとは思ってるのですが、既存の動きを壊さずに対処する方法が思いつかないのが現状です。

**Comment by MaxfieldWalker** [comment]
早速の返信ありがとうございます。

動作の理由や対処法がはっきりして納得することができました。
なんとかReactivePropertyはそのままに複数ウィンドウに対応できるようにやってみます。

ありがとうございました😉
