### ISSUE TITLE
Advantages over reactiveui

### ISSUE THREAD

**Issue by RedEyedDog** [runceel/ReactiveProperty#367]
Hi,

I was wondering if you could outline some of the advantages over ReactiveUI?

I have used ReactiveUI before and found it quite clunky

Thanks

**Comment by runceel** [comment]
Hi, @RedEyedDog 

I don't know ReactiveUI enough. But I can write concept of ReactiveProperty.

ReactiveProperty consists of a few core classes such as `[ReadOnly]ReactiveProperty[Slim]<T>` and `[Async]ReactiveCommand`, and many extension methods. 
All core classes are NOT as base class of user code. I guess this is one of biggest points what is different of concept between ReactiveUI and ReactiveProperty. In my understanding, ReactiveUI has base class what name is `ReactiveObject`. So, you can use any base classes you want to use when you use ReactiveProperty.

This is a minimum ViewModel class using ReactiveProperty:

```csharp
class MainPageViewModel : IDisposable
{
  private readonly CompositeDisposable _disposable = new();
  public ReactivePropertySlim<string> Input { get; } // Input
  public ReadOnlyReactivePropertySlim<string> UpperCase { get; } // This is set uppercase of Input 1 sec later

  public MainPageViewModel()
  {
    Input = new ReactivePropertySlim<string>("").AddTo(_disposable);
    UpperCase = Input.Delay(TimeSpan.FromSeconds(2)).Select(x => x.ToUpper())
      .ToReactivePropertySlim()
      .AddTo(_disposable);
  }

  public void Dispose() => _disposable.Dispose();
}
```

I think easy to understand if you know Rx.

But you have to pay costs to use ReactiveProperty on XAML files. You have to add `.Value` to binding path like below:

```xml
<TextBlock Text="{Binding UpperCase.Value}" />
```

This is base concept of ReactiveProperty. What do you think?
If you want to know more, please check [ReactiveProperty document](https://okazuki.jp/ReactiveProperty/).

**Comment by RedEyedDog** [comment]
Yea i like it
I think reactiveUI offers a lot more ( in some cases more noise) but i really like the syntax with this, its fluent etc and is all you need in most cases. Thanks for the outline.. looking forward to using it.

**Comment by sgf** [comment]
Even though it is a huge improvement compared to ReactiveUI, it seems to be a bit more complicated compared to front-end development (Web). For example, two-way binding such as vue is very simple to use.
