### ISSUE TITLE
Update to System.Reactive v3.1.0

### ISSUE THREAD

**Issue by MovGP0** [runceel/ReactiveProperty#38]
The project should be updated to `System.Reactive.xxx` version 3.1.0, in order to support newer projects. 

Currently a project that references the new version of `System.Reactive` as well as `ReactiveProperty` gets an compile error.

**Comment by runceel** [comment]
Thank you for your suggestion.

I'm working now. Please wait a moment.

**Comment by runceel** [comment]
I released ReactiveProperty v3.3.1.

I updated System.Reactive v3.0.0 to v3.1.0.
Please try this release.

**Comment by MovGP0** [comment]
It's working now. Thanks!
