### ISSUE TITLE
AsyncReactiveCommand の CanExecuteを別スレッドから変更すると、「'このオブジェクトは別のスレッドに所有されているため、呼び出しスレッドはこのオブジェクトにアクセスできません。」の例外が発生する。

### ISSUE THREAD

**Issue by kenichi-kobayashi** [runceel/ReactiveProperty#382]
いつもお世話になってます。

以下の現象がありましたので、報告させてください。

■現象
AsyncReactiveCommand の CanExecuteを別スレッドから変更すると、「'このオブジェクトは別のスレッドに所有されているため、呼び出しスレッドはこのオブジェクトにアクセスできません。」の例外が発生しました。

■詳細

・Textプロパティを用意する。
・TextプロパティがNullOrEmptyでなければ、実行可能なコマンドを用意する。
・ReactiveCommandと、AsyncReactiveCommandの２つのコマンドを用意する。
・画面では、Buttonに２つのコマンドをBindする。
・TextプロパティをUIスレッド以外から変更する。
・AsyncReactiveCommandだけが例外となる。

![image](https://user-images.githubusercontent.com/47070699/171007693-632cd827-faee-4d72-9398-46e6111ee921.png)

[ReactivePropertyUIThread.zip](https://github.com/runceel/ReactiveProperty/files/8798916/ReactivePropertyUIThread.zip)

これは、仕様でしょうか？

よろしくお願いいたします。

**Comment by runceel** [comment]
仕様になります。
ObserbeOn で UI スレッドに手動で切り替えてください。

UI スレッドへのイベントの自動ディスパッチ機能は ReactiveProperty/ReadOnlyReactiveProperty/ReactiveCommand のみになります。
自動ディスパッチは便利なのですが、わかりにくい挙動も引き起こすため AsyncReactiveCommand や ReactivePropertySlim/ReadOnlyReactivePropertySlim にはありません。

**Comment by kenichi-kobayashi** [comment]
いつも、即レスに感謝です。

そういう仕様ということで、理解しました！
