### ISSUE TITLE
Is ReactivePropertySlim thread safe?

### ISSUE THREAD

**Issue by ptasev** [runceel/ReactiveProperty#390]
Is `ReactivePropertySlim` supposed to be thread safe? It seems to me the `Subscribe` and private `UnsubscribeNode` methods may not be if I'm not mistaken.

https://github.com/runceel/ReactiveProperty/blob/41f547c6c45a5389ad4999bbec20239579d83592/Source/ReactiveProperty.Core/ReactivePropertySlim.cs#L160-L170

**Comment by runceel** [comment]
`ReactivePropertySlim` is NOT thread safe.
So if you access to `ReactivePropertySlim` from multiple threads, please use lock, Mutex and others.
