### ISSUE TITLE
DLL versions installed by NuGet is not updated from 1.0.0

### ISSUE THREAD

**Issue by espresso3389** [runceel/ReactiveProperty#40]
We are using MSI based installer on Windows.
And MSI normally check the update of each exe/dll file by its associated version.
The problem is that RectiveProperty related DLLs have 1.0.0 for recent releases.

Do you have any plan to increment the version for future releases?

**Comment by runceel** [comment]
Thank you for your feedback.

I released 3.2.2. 
This version setted to assembly version "3.2.2".

If I'll forget increment then you feedback again please.

**Comment by espresso3389** [comment]
I've confirmed that the latest version 3.2.2 correctly has the version 3.3.2 on its assemblies.
Thanks so much for the update!
