### ISSUE TITLE
Add IReadOnlyCollection<T>.ObserveElementProperty()

### ISSUE THREAD

**Issue by hsytkm** [runceel/ReactiveProperty#407]
First of all, I would like to thank you for maintaining this awesome library.
I use it in my personal tools for a WPF application.

I thought it would be convenient if there is `IReadOnlyCollection<T>.ObserveElementProperty()`.
I use it in situations where the list elements are fixed and only the elements value is changed.

In such situations, I think I have to create an `ObservableCollection<T>` like so.
If you know of a good way, please let me know.

---

いつもありがたく利用させていただいております！

早速ですが、 `IReadOnlyCollection<T>.ObserveElementProperty()` があれば便利かと思いました。
コレクションは固定で、値のみが変化するシチュエーションで使用します。

このような場合、以下のように `ObservableCollection<T>` を生成する必要があると思っています。
代替方法ありましたらご紹介ください。

```cs
// <PackageReference Include="CommunityToolkit.Mvvm" Version="8.1.0" />
// <PackageReference Include="ReactiveProperty" Version="9.0.0-pre202301080724" />
using System.Collections.ObjectModel;
using CommunityToolkit.Mvvm.ComponentModel;
using Reactive.Bindings.Extensions;
using Reactive.Bindings.TinyLinq;

// fixed length array
C[] array = Enumerable.Range(0, 3).Select(x => new C(x)).ToArray();

Console.WriteLine("Initialize");
ObserveElementsFromOtherContext(array);

Console.WriteLine("Set values");
for (int i = 0; i < array.Length; i++) array[i].Value = i;
array[0].Value = await HeavyCalculationAsync();

static void ObserveElementsFromOtherContext(IReadOnlyCollection<C> roCollection)
{
    // I want to write...
    //roCollection.ObserveElementProperty(x => x.Value)...

    // I write as below. (I don't want to create oc.)
    new ObservableCollection<C>(roCollection)
        .ObserveElementProperty(x => x.Value)
        .Select(pack => pack.Instance)
        .Subscribe(Console.WriteLine);
}

static async Task<double> HeavyCalculationAsync()
{
    await Task.Delay(2000);
    return 1.23;
}

partial class C : ObservableObject
{
    public int Index { get; }
    [ObservableProperty] double _value = double.NaN;
    public C(int index) => Index = index;
    public override string ToString() => $"[{Index}] : {Value}";
}
```

**Comment by runceel** [comment]
Thank you for your feedback.
I'm working on this! And I will release this feature with v9.0.0.

**Comment by hsytkm** [comment]
Thank you for your prompt response!
I'm looking forward to the release of  v9.0.0!

**Comment by runceel** [comment]
@hsytkm 
I have implemented this feature on #408. However I noticed that this makes misunderstanding on following case;

```csharp
Person[] people = new[] { new Person { ... }, new Person { ... } };
people.ObserveElementProperty(x => x.FirstName).Subscribe(... do something ...);

// replace to another instance
people[1] = new Person { ... };
people[1].FirstName = "xxx"; // You can't notice this change.
```
Extension methods mislead the user into thinking that the collection itself is being monitored. However, it actually monitors the elements of the collection at that point in time.

So, I'm thinking that change this to static method from extension method;

```csharp
Person[] people = new[] { new Person { ... }, new Person { ... } };
CollectionUtilities.ObserveElementProperty(people, x => x.FirstName).Subscribe(... do something ...);
```

What do you think?

**Comment by hsytkm** [comment]
Thank you for your feedback!
I think you are right, making it an extension method would reduce misuse by users.

I'm not very familiar with library design, but it's a bit strange that the argument is IEnumerable\<T\>.
If observed instances haven't been created, wouldn't users be referring different instances?

Please let me know what you think.

```cs
var peopleSequence = Enumerable.Range(40, 3).Select(age => new Person(age));

CollectionUtilities
    .ObserveElementProperty(peopleSequence, x => x.Value)
    .Select(pack => pack.Instance)
    .Subscribe(Console.WriteLine);

foreach (var person in peopleSequence)
    person.Age = 18;
```

**Comment by runceel** [comment]
I have just released a pre-release package what includes this feature.

https://www.nuget.org/packages/ReactiveProperty/9.0.0-pre202302040959

**Comment by runceel** [comment]
I totally agree you. So I chaged the argument type from `IE<T>` to `IRC<T>`.

**Comment by hsytkm** [comment]
I confirmed the new extension method with the latest package.
I got the behavior I wanted!
I appreciate your kind action.
