### ISSUE TITLE
ReactiveCommandSlim.Execute checks a CanExecute state, but ReactiveCommand.Execute does not

### ISSUE THREAD

**Issue by emaame** [runceel/ReactiveProperty#412]
It's hard to say what is correct for me... (I couldn't find out `ICommand` spec)

When `ReactiveCommand.Execute` is called directly, it never checks a `CanExecute` state.
However `ReactiveCommandSlim.Execute` does check a `CanExecute` state like `AsyncReactiveCommand.Execute`.

https://github.com/runceel/ReactiveProperty/blob/main/Source/ReactiveProperty.NETStandard/ReactiveCommand.cs#L135
https://github.com/runceel/ReactiveProperty/blob/main/Source/ReactiveProperty.Core/ReactiveCommandSlim.cs#L163
https://github.com/runceel/ReactiveProperty/blob/main/Source/ReactiveProperty.Core/AsyncReactiveCommand.cs#L174

It looks reasonable changes. However 

1. Please write about changes between `ReactiveCommand.Execute` and `ReactiveCommandSlim.Execute` (Breaking change?).

2. How about providing `ReactiveCommand.ForceExecute` that always executes for compatibility.
I guess it is preferred than disable checking a `CanExecute` state for compatibility to `ReactiveCommand.Execute`.

----

私にはなんとも言いがたいのですが（`ICommand` の仕様がどこにあるのか分かりませんでした） 

`ReactiveCommand.Execute` を直接呼んだ場合は、無条件に実行されます（ `CanExecute` はみない）。
しかし `ReactiveCommandSlim.Execute` を直接呼んだ場合は、 `AsyncReactiveCommand.Execute` と同様に `CanExecute` がチェックされます。

妥当な変更だと思うのですが、以下の 2 点をご検討頂けないでしょうか

1. この挙動の違いについて、互換性の喚起をお願いできないでしょうか？（破壊的変更？）
（`ReactiveCommand.Execute` とは `CanExecute == false` の場合の挙動が変わっている旨）

2. また、汚い＆問題なければなのですが、 `ReactiveCommand.Execute` 相当の、`ReactiveCommand.ForceExecute` といったメソッドを設けて頂けませんか？
理屈としては `CanExecute` の管理ミスを直すべきですが、移行パスというか、何かの時にという程度のものがあっても良いのかな、、と思います。無い方が良いのかもです。ただ、 `ReactiveCommand.Execute` に合わせるよりは良いのかなぁと思っています（ここが私見ではなんとも言いがたい部分です）。

よろしくお願いいたします。

**Comment by runceel** [comment]
@emaame Thank you for your feedback.

For 1. I will write it to documentation. For now, I add it to the release note.

For 2. I will not add `ForceExecute` method you mentioned. Because if you want to call a method what is called when `Execute` method was called, the best way is just call the method directly.

```cs
var command = someIObservableBoolObject.ToReactiveCommandSlim()
    .WithSubscribe(DoSomething);

// command.Execute(); // this line checks `CanExecute` state.
DoSomething(); // this line doesn't check it.
```
