### ISSUE TITLE
Add ValidatableReactiveProperty<T>.ObserveValidationErrorMessage

### ISSUE THREAD

**Issue by eagle628** [runceel/ReactiveProperty#413]
Nice to meet you, I have always used this library.

The only difference between ReactiveProperty<T> and ValidatableReactiveProperty<T> is whether or not to automatically switch to the UIDispatcher.

However, while the regular ReactiveProperty<T> has an extension method to get error messages in IObservable<string?>, the ValidatableReactiveProperty<T> does not.
I see no particular reason for not having it, and would like to see it added.

The reason is that the argument type of the relevant extension method is only ReactiveProeprty<T>. However, I think it is too broad for IReactiveProperty<T>, so I think it would be better to establish a new method with the same contents, etc.

```c#
//In ReactivePropertyExtensions.cs
/// <summary>
/// Create an IObservable instance to observe validation error messages of ReactiveProperty.
/// </summary>
/// <typeparam name="T">Property type</typeparam>
/// <param name="self">Target ReactiveProperty</param>
public static IObservable<string?> ObserveValidationErrorMessage<T>(this ReactiveProperty<T> self) =>
    self.ObserveErrorChanged
        .Select(x => x?.OfType<string>()?.FirstOrDefault());
```

----

初めまして、いつもこのライブラリを利用させていただいております。

ReactiveProeprty＜T>とValidatableReactiveProperty＜T>は違いは、自動でUIDispatcherに切り替えるかどうかのみである。
しかし、通常のReactiveProperty<T>には、エラーメッセージをIObservable<string?>で取得する拡張メソッドがある一方で、ValidatableReactiveProperty＜T>にはない。特に実装していないことの理由はないと思いますので、追加してほしい。

該当の拡張メソッドの引数の型がReactiveProeprty＜T>のみになっているのが原因。とはいえ、IReactiveProerpty＜T>では広すぎると思いますので、同じ内容のメソッドを新設するなどがいいのかなと思います。

以上、よろしくお願いいたします

**Comment by runceel** [comment]
@eagle628 Thank you for your feedback.
ˋValidatableReactiveProperty<T>ˋ doesn't have ˋObserveValidationErrorMessageˋ extension method. 
Because the class has ˋErrorMessageˋ property. Most commonly use case of ˋObserveValidationErrorMessageˋ is to create a new ˋReactiveProperty<string>ˋ for error message. 
In this case, you can just use ˋErrorMessageˋ property like below:
https://github.com/runceel/ReactiveProperty/blob/main/Samples/ReactivePropertyCoreSample.WPF/Views/ValidationWindow.xaml#L26

If you have any other use cases for ˋObserveValidationErrorMessageˋ, please let me know.

**Comment by eagle628** [comment]
@runceel 
Sorry. I didn't check the sample.  I didn't realize that the property was in ValidatableReactiveProperty<T>.

I made this Issue because I was lost when I tried to replace from ReactiveProeprty<T> to the added ValidatableReactiveProperty<T>.
I have been using the code from [the linked article](https://qiita.com/okazuki/items/7572f46848d0e93516b1#%E5%85%A5%E5%8A%9B%E5%80%A4%E3%81%AE%E3%83%90%E3%83%AA%E3%83%87%E3%83%BC%E3%82%B7%E3%83%A7%E3%83%B3-slim-%E3%81%AB%E3%81%AF%E7%84%A1%E3%81%84%E6%A9%9F%E8%83%BD) to display error messages wherever I want by IObservable<T> to ToReadOnlyReactiverPropertySlim().

```c#
using Reactive.Bindings;
using System;

namespace ConsoleApp2
{
    class Program
    {
        static void Main(string[] args)
        {
            var rp = new ReactiveProperty<string>()
                .SetValidateNotifyError(x => string.IsNullOrEmpty(x) ? "必須だよ" : null);
            rp.ObserveValidationErrorMessage()
                .Subscribe(x => Console.WriteLine($"エラーメッセージが変わったよ {x}"));

            rp.Value = "okazuki";
            rp.Value = null;
        }
    }
}
```

If you have an alternative, no problem. (A bit of a pain to get the word out...)

Thanks for your responding.
