### ISSUE TITLE
DependencyObject.ToReactiveProperty<T>(DependencyProperty) でTwoWayバインディングが動作しない

### ISSUE THREAD

**Issue by koara-local** [runceel/ReactiveProperty#42]
便利なライブラリの公開ありがとうございます。私的な開発で大変助かっております。

１点、ReactiveProperty 3.4.0で追加された、DependencyObjectの拡張メソッドの `ToReactiveProperty` についての質問があります。

[ReactiveProperty 3.4.0をリリースしました - かずきのBlog@hatena](http://blog.okazuki.jp/entry/2016/11/30/222201)

現象としましてはUserControlのTwoWayバインディングで、Dependency Propertyから生成したReactive Propertyからの変更が反映されないという状況です。質問としましては、この拡張メソッドは、仕様として Dependency Property => Reactive Property の単方向での変更しかサポートしてないのでしょうか？

[ReactiveProperty/DependencyObjectExtensionsTest.cs at d935b7353937b3dcb20f3be1d0c4ab0b6d9b7ec7 · runceel/ReactiveProperty](https://github.com/runceel/ReactiveProperty/blob/d935b7353937b3dcb20f3be1d0c4ab0b6d9b7ec7/Test/ReactiveProperty.Tests/Extensions/DependencyObjectExtensionsTest.cs#L50)

上記のテストでも、`Dependency Property => Reactive Property` の単方向の更新のみ反映されるような仕様であるように見受けられます。

```csharp
// テスト抜粋
            rp.Value = "homuhomu";
            rp.Value.Is("homuhomu");
            target.Name.Is("kimura");
```

今回、私のユースケースとしては ` Reactive Property => Dependency Property`  の変更の伝播、といいますか双方向の更新をさせたいのですが、正しい実装としてはどのように実装すればよいでしょうか？

```csharp
// このように動作させたい
            rp.Value = "homuhomu";
            rp.Value.Is("homuhomu");
            target.Name.Is("homuhomu");
```

現状は以下のようにしてひとまず対処している状態です。（変更が循環してるような気がしますが、ひとまずは双方向の動作をしています）

```csharp
var rp = target.ToReactiveProperty<string>(Person.NameProperty);
rp.Subscribe(x => target.Name = x );
```

**Comment by runceel** [comment]
今のところ一方通行での同期を考えています。

双方向でやりたいときは普通にBindingすればいいと思ってるので。

**Comment by koara-local** [comment]
> 双方向でやりたいときは普通にBindingすればいいと思ってるので。

たしかにDependency Property に普通にBindingすれば双方向で動作しますね・・・。自分の知識不足でした、お手数おかけしました。

自分が以下のような感じで、ViewModelを作成してBindingした場合に、ReactivePropery => Dependency Propertyへの同期がされないなと考えて困っておりました。(意図としてはUserControl側の変更を上位ののコントロールに返したい）

View: [ReactivePropertyUserControlSample/RxPUserControl.xaml at master · koara-local/ReactivePropertyUserControlSample](https://github.com/koara-local/ReactivePropertyUserControlSample/blob/master/WpfApplication3/RxPUserControl.xaml)
ViewModel: [ReactivePropertyUserControlSample/RxPUserControl.xaml.cs at master · koara-local/ReactivePropertyUserControlSample](https://github.com/koara-local/ReactivePropertyUserControlSample/blob/master/WpfApplication3/RxPUserControl.xaml.cs)

**Comment by koara-local** [comment]
たしかに双方向のBindingをしたいときに、ReactiveProperty => Dependency Propertyの同期は必要なさそうですね。ご回答いただきありがとうございました。
