### ISSUE TITLE
ReactivePropertyのSubscribe内の例外発生時の挙動について

### ISSUE THREAD

**Issue by SabastianGambrell** [runceel/ReactiveProperty#420]
いつもお世話になっております。

現在、作成しているアプリケーションでは、例外発生時においては、個別にTryCatchして処理するのではなく、DispatcherUnhandledException にて刈り取って、すべての例外を包括的に処理するようにしています。

```
    public partial class App : Application
    {
        protected override void OnStartup(StartupEventArgs e)
        {
            base.OnStartup(e);

            //① ReactivePropertyの変更がUIスレッド上で発生するようにする。
            ReactivePropertyScheduler.SetDefault(new ReactivePropertyWpfScheduler(this.Dispatcher));

            //② UIスレッドで発生した未処理例外を捕獲する。
            DispatcherUnhandledException += (ss, ee) => {
                MessageBox.Show(ee.ToString());
                ee.Handled = true;
            };
        }
    }

```

以降、この処理を「集約例外」と呼びます。

上記のとおりにした状態で、ReactivePropertyのSubscribe内の例外発生時の挙動について、以下の2点が想定外の動作をしていたので報告させてください。

１）RpのSubscribe内の例外を集約例外で刈り取ると、2回目以降Subscribeが発火しない。
２）BehaviorからRp.Valueを更新すると集約例外で捕獲できない。

上記の現象を再現できるサンプルプログラムを以下のとおりに作成しました。
https://github.com/SabastianGambrell/CatchReactivePropertyExceptions

上記をVSでデバック起動すると、以下の画面が表示されます。

![image](https://user-images.githubusercontent.com/115391518/232265404-e3101a93-5b8b-45c5-8f4d-df2948463497.png)

以下のように、SelectedItemsが更新された場合に、「例外を発生させる場合」にチェックが入っている状態であれば、例外が発生するようになっています。

```
            SelectedItems.Where(a => a != null).Subscribe(a =>
            {
                if (IsException.Value) throw new ApplicationException();
                else a.ForEach(b => System.Console.WriteLine(b.Name));
            }).AddTo(disposables);
```

### １）RpのSubscribe内の例外を集約例外で刈り取ると、2回目以降Subscribeが発火しない。

まずは１）を確認するために、左下の「例外を発生させる場合」にチェックが入っている状態で、右下の「Test」ボタンを押下してみてください。

初回の押下時においては、正しく集約例外で処理され、以下のようにメッセージが表示されます。

![image](https://user-images.githubusercontent.com/115391518/232265443-ad1d494e-07c0-4331-8caf-e09eab1a6bb7.png)

２回目以降においては、そもそもSubscribeが発火しません。
これは何が理由でしょうか？

### ２）BehaviorからRp.Valueを更新すると集約例外で捕獲できない。

次に２）を確認するために、上記アプリを再起動してください。
左下の「例外を発生させる場合」にチェックが入っている状態で、DataGridの任意の行を選択してみてください。
VS上だと、例外が発生することが確認できますが、集約例外で捕獲することができません。

しかし、Behaviorから更新されても、ObserveOnUIDispatcher を実行すると、集約例外で捕獲できます。

```
            // ※ Behaviorから更新されても、ObserveOnUIDispatcher を実行すると、集約例外で捕獲できる。
            SelectedItems.Where(a => a != null).ObserveOnUIDispatcher().Subscribe(a =>
            {
                if (IsException.Value) throw new ApplicationException();
                else a.ForEach(b => System.Console.WriteLine(b.Name));
            }).AddTo(disposables);
```

また、Behaviorから更新されても、asyncメソッドにすると、集約例外で捕獲できます。

```
            // ※ Behaviorから更新されても、asyncメソッドにすると、集約例外で捕獲できる。
            SelectedItems.Where(a => a != null).Subscribe(async a =>
            {
                await Task.CompletedTask;
                if (IsException.Value) throw new ApplicationException();
                else a.ForEach(b => System.Console.WriteLine(b.Name));
            }).AddTo(disposables);
```

忙しいところすいませんが、ご確認のほど、よろしくお願いします。

**Comment by runceel** [comment]
@SabastianGambrell 
ご質問ありがとうございます。どちらも ReactiveProperty ではない別の部分の仕様に起因するものです。

1. Reactive Extensions が onNext 中に例外が発生すると Dispose が呼ばれて以降の処理が行われなくなる仕様のせいです。
2. データバインディング中に発生した例外は WPF のほうでハンドリングされるためです。ObserveOnUIDispatcher や await Task.CompletedTask; を挟むとデータバインディングによる値の同期とは違うタイミングで例外が発生するようになるので集約例外にいくようになります。なので WPF の仕様です。

そのため、Subscribe 内では例外は throw させないほうが良いです。
すべての Subscribe に例外処理を挟むのが大変であれば、こんなものを入れておくといいかもしれません。

単体テスト時に任意のエラーハンドリングを差し込める余地を入れる感じで以下のようなものを用意。
```csharp
using System;
using System.Windows;

namespace WpfApp5
{
    public interface IErrorHandler
    {
        void HandleError(Exception ex);
    }

    public static class ErrorHandler
    {
        private static IErrorHandler _instance;
        public static IErrorHandler Instance
        {
            get
            {
                if (_instance == null)
                {
                    _instance = new DefaultErrorHandler();
                }
                return _instance;
            }
            set
            { 
                _instance = value; 
            }
        }
    }

    public class DefaultErrorHandler : IErrorHandler
    {
        public void HandleError(Exception ex)
        {
            MessageBox.Show(ex.ToString());
        }
    }
}
```

Subscribe のかわりに呼ぶメソッド
```csharp
    public static class ObservableExtensions
    {
        public static IDisposable SubscribeWithErrorHandling<T>(this IObservable<T> observable, Action<T> onNext)
        {
            return observable.Subscribe(x =>
            {
                try
                {
                    onNext(x);
                }
                catch (Exception ex)
                {
                    ErrorHandler.Instance.HandleError(ex);
                }
            });
        }
    }
```

Subscribe のかわりに、上で定義したコードを呼ぶ。
```csharp
// Behaviorから更新されると、DispatcherUnhandledException で捕獲できない。
SelectedItems.Where(a => a != null).SubscribeWithErrorHandling(a =>
{
    if (IsException.Value) throw new ApplicationException();
    else a.ForEach(b => System.Console.WriteLine(b.Name));
}).AddTo(disposables);
```

**Comment by SabastianGambrell** [comment]
早速の回答ありがとうございました。
そして、返信が遅くなってすいません。

本件、了解いたしました。

今後とも、よろしくお願いいたします。
