### ISSUE TITLE
Join .NET Foundation

### ISSUE THREAD

**Issue by eder-careplus** [runceel/ReactiveProperty#428]
Hi Runceel, I was wondering if it wouldn't be a good idea to you to make ReactiveProperty a project supported by .NET Foundation like Rx.Net here:
https://dotnetfoundation.org/projects/project-detail/reactive-extensions-for-.net

I don't know the benefits of that, if there's any but I think it could help to reduce Big companies resistance to adopt it.
My trye wish is that MSFT would incoporate ReactiveProperty as part of BCL and officially suport it.

**Comment by runceel** [comment]
Hi @eder-careplus,
Thank you for your suggestion. I really appreciate it.
If ReactiveProperty joined .NET Foundation, it would have a lot of benefits like you said. However, I'm unable to spend time on the many processes required to join and work for .NET Foundation.
I'm sorry, but I won't be able to join it.
