### ISSUE TITLE
Package for maui?

### ISSUE THREAD

**Issue by Strypper** [runceel/ReactiveProperty#439]
I see you have a lot of packages out there, but which one are for MAUI?

**Comment by runceel** [comment]
@Strypper 
There are no any packages for MAUI specific version.
You can use `ReactiveProperty` package or `ReactiveProperty.Core` package on MAUI because the packages are built for .NET 7.

**Comment by runceel** [comment]
@Strypper If you have another question, feel free create or reopen an issue.
