### ISSUE TITLE
FilteredReadOnlyObservableCollectionのSource.CollectionChangedへのイベント購読が、Dispose時に購読解除できていないようです。

### ISSUE THREAD

**Issue by ryo1988** [runceel/ReactiveProperty#450]
https://github.com/runceel/ReactiveProperty/blob/a5590692978043ab3ab8e844e2294b25d4a08f50/Source/ReactiveProperty.NETStandard/Helpers/FilteredReadOnlyObservableCollection.cs#L351C55-L351C55

CollectionChanged -= Source_CollectionChanged;

となっていますが、

Source.CollectionChanged -= Source_CollectionChanged;

である必要がありそうです。

**Comment by runceel** [comment]
@ryo1988 ありがとうございます。マージしました。近いうちにリリースします。

**Comment by runceel** [comment]
プレビューパッケージとして公開しました。
特に問題なければ、このままリリース版として公開予定です。

https://www.nuget.org/packages/ReactiveProperty.WPF/9.3.4-pre202310290551

**Comment by ryo1988** [comment]
リリースありがとうございます。

**Comment by runceel** [comment]
@ryo1988 
すいません。元記事に英文書き足しました。
