### ISSUE TITLE
Breaking change in Ver 9.3.1

### ISSUE THREAD

**Issue by hsytkm** [runceel/ReactiveProperty#452]
# Breaking change in Ver 9.3.1

## Introduction

I think a breaking change has occurred.
But I have limited knowledge of schedulers.
If there are any problems with my implementation, please let me know.

 ## Platform with bug

WPF

 ## Description

After the `ReactiveTimer` timer starts in Rp Ver9.3.1, subsequent processing is **not** executed.

```cs
private void Application_Startup(object sender, StartupEventArgs e)
{
    ReactivePropertyScheduler.SetDefault(new ReactivePropertyWpfScheduler(Dispatcher));

    var timer = new ReactiveTimer(TimeSpan.FromSeconds(1), ReactivePropertyScheduler.Default);
    timer.Start();

    // If Rp is Ver9.3.1, it will not reach here.
}
```

 ## Steps to Reproduce

1. Set `ReactivePropertyWpfScheduler` to Rp’s scheduler in `Application.Startup`.
2. Create `ReactiveTimer` with `ReactivePropertyScheduler.Default`.
3. Start the timer of the created `ReactiveTimer`.

 ## Expected behavior

Subsequent processing is executed after `ReactiveTimer` starts.

 ## Actual behavior

Subsequent processing is **not** executed after `ReactiveTimer` starts.

 ## Combination confirmation results

|                                 | 9.3.0 | 9.3.1  |
| ------------------------------- | ----- | ------ |
| SynchronizationContextScheduler | OK    | OK     |
| ReactivePropertyWpfScheduler    | OK    | **NG** |

## Environment

- VisualStudio 2022 17.7.6
- net48, net6.0-windows
- ReactiveProperty.WPF 9.3.1

## Reproduction Repo

https://github.com/hsytkm/Rp931WpfBreakingChangeDemo

**Comment by runceel** [comment]
@hsytkm I just published a preview package includes a change for this issue.
Please check it. And if you found an issue related this, please let me know.

https://www.nuget.org/packages/ReactiveProperty.WPF/9.3.4-pre202310290551

**Comment by hsytkm** [comment]
@runceel I confirm that the expected behavior is working. Thank you for your prompt response!
