### ISSUE TITLE
Blazor Server validation does not work

### ISSUE THREAD

**Issue by gmkado** [runceel/ReactiveProperty#460]
Am I doing something wrong?  

I initially tried adding `ReactivePropertiesValidator` to my application but it wasn't working, so I cloned this repo and ran the `BlazorServerApp` sample to poke around and see how things worked.

First I got an error when trying to compile:
> Error NU1605 : Warning As Error: Detected package downgrade: System.Reactive from 6.0.0 to 5.0.0

So I changed [this line](https://github.com/runceel/ReactiveProperty/blob/f9445577145ca16c7d590978300e2a710620fe41/Samples/Blazor/BlazorSample.Shared/BlazorSample.Shared.csproj#L12) to 6.0.0 and it ran okay, but it does not correctly validate the name fields:
![image](https://github.com/runceel/ReactiveProperty/assets/6592135/443aeafe-568f-4bd1-99c4-85e8af1647d8)

Thanks in advance

**Comment by runceel** [comment]
@gmkado
Thank you for asking.

It seems to be working correctly. Validation rules for `FirstName` and `LastName` properties are `Required` and `StringLength(maximumLength: 10)`. 'a' and 'b' are correct values for those properties.

![image](https://github.com/runceel/ReactiveProperty/assets/79868/9c6dc992-9f40-456c-9744-1a571ff4f33e)

And I'm working for ReactiveProperty for .NET 8 Blazor. However, it's very tough to work with `ReactivePropertyValidator` for new Static SSR model. I have no idea for it now.
If you are going to use it on Statis SSR model or WASM model, I recommend using another solution for validation.

**Comment by gmkado** [comment]
@runceel thanks for the response, I misunderstood that `StringLength` was a maximum, not a minimum
