### ISSUE TITLE
No way to raise a PropertyChanged notification from derived class

### ISSUE THREAD

**Issue by hayer** [runceel/ReactiveProperty#473]
When deriving from `ReactiveProperty<T>` or `ReactivePropertySlim<T>` there is no way to invoke the `PropertyChangedEventHandler? PropertyChanged;`.

Suggest to add something like `OnPropertyChanged` based on [Microsofts Learn example](https://learn.microsoft.com/en-us/dotnet/csharp/programming-guide/events/how-to-raise-base-class-events-in-derived-classes).

**Comment by runceel** [comment]
I have released a new package.
https://github.com/runceel/ReactiveProperty/releases/tag/9.5.0
