### ISSUE TITLE
ReactiveProperty Version 3.6.0.0 references wrong version of System.Reactive.Interfaces

### ISSUE THREAD

**Issue by E812** [runceel/ReactiveProperty#49]
The actual ReactiveProperty, Version 3.6.0.0 references System.Reactive.Interfaces, Version 3.0.0.0 instead of Version 3.0.1000.0

**Comment by neuecc** [comment]
Install ReactiveProperty
Install reactiveui

![image](https://cloud.githubusercontent.com/assets/46207/24585541/f3040d10-17c7-11e7-9bd9-f83a4a228305.png)

This issue is not about ReactiveProperty.
reactiveui is dependent old-rx package(Rx-Main), this causes terrible issue.
But reactiveui is not fixed yet. https://github.com/reactiveui/ReactiveUI/issues/1139

**Comment by E812** [comment]
I am not using reactiveui. I use ReactiveProperty for the ViewModel classes in my WPF application.
When I install the ReactiveProperty 3.6 package from Nuget it also installs the System.Reactive 3.1.1 packages as a dependency. I then checked my compiled assemblies with AsmSpy and it found ReactiveProperty.dll Version 3.6.0.0 references System.Reactive.Interfaces.dll Version 3.0.0.0. This is wrong as the Nuget package for System.Reactive 3.1.1 comes with a System.Reactive.Interfaces.dll in Version 3.0.1000.0.
I am not sure about the dependencies of ReactiveUI, but as they seem to stick with the older RxMain packages they should not reference the actual ReactiveProperty nuget packages.

**Comment by runceel** [comment]
@E812 
I'll look this issue. Sorry for my slow response.

**Comment by ventsislav-georgiev** [comment]
I have the same issue:
ReactiveProperty, Version 3.6.0.0 references System.Reactive.Interfaces, Version 3.0.0.0
ReactiveProperty.NET46, Version 3.6.0.0 references System.Reactive.Interfaces, Version 3.0.1000.0

and the latest nuget package for System.Reactive 3.1.1 is 3.0.1000.0

**Comment by runceel** [comment]
hmm...

I think that this is Reactive Extension's issue.

I tried this step.

- I created .NET Standard library project.
- Add System.Reactive 3.1.1 package.
- Build project.
- Check asmspy output.

<img width="747" alt="default" src="https://cloud.githubusercontent.com/assets/79868/26809942/662380ec-4aa3-11e7-806d-edbc0cb7bb53.PNG">

System.Reactive.Interfaces version 3.0.0.0 appered. What can I do for this issue?

**Comment by ventsislav-georgiev** [comment]
I see, it seems this is a big issue with pre v4 of System.Reactive - https://github.com/Reactive-Extensions/Rx.NET/issues/205

Can we get a ReactiveProperty version based upon the v4 preview version System.Reactive where this issue is fixed?

**Comment by runceel** [comment]
Hi.

I released ReactiveProperty v4.0.0-pre1.
https://www.nuget.org/packages/ReactiveProperty/4.0.0-pre1

Please try it!

Release note is follows:
https://github.com/runceel/ReactiveProperty/blob/vNext/ReleaseNote.md

**Comment by runceel** [comment]
I close this issue.
If you have some issue then reopen this issue or create new issue.

Thank you.
