### ISSUE TITLE
Support for more complex async ReactiveCommands

### ISSUE THREAD

**Issue by BADF00D** [runceel/ReactiveProperty#5]
Hello,
I had a problem for which I couldn't find a solution in your library. I want to perform an async task in my demo app.
The view-model: 
```csharp
public class ViewModel {
	public ReactiveProperty<string> FamilyName { get; private set; }
	public ReactiveCommand StoreUserCommand { get; private set; }
	public ReactiveProperty<string> Status { get; private;}
}
```
Storing a user takes a lot of time, so I want to perform this command asynchronous. So my ctor looks like this:

```csharp
public ViewModel() {
	FamilyName = new ReactiveProperty<string>();
	Status = new ReactiveProperty<string>();
	
	StoreUserCommand = FamilyName
			.Select(s => !string.IsNullOrWhiteSpace(s) && s.Length > 5)
			.ToReactiveCommand();
	StoreUserCommand.Subscribe(async _=> {
		await Task.Delay(1000);//storing user take some time
		MessageBox.Show("Done");
	});
}
```
This solution makes the StoreUserCommand perform async, but it does not disable the button I bound it to. So I came up with this solution to initialize the command:
```csharp
var isExceuting = new ReplaySubject<bool>(1);
isExceuting.OnNext(false);
StoreUserCommand = FamilyName
	.Select(s => !string.IsNullOrWhiteSpace(s) && s.Length > 5)
	.CombineLatest(isExceuting, (ce, ie) => ce && !ie)
	.ToReactiveCommand();

StoreUserCommand.Subscribe(async _ => {
	isExceuting.OnNext(true);
	await Task.Delay(1000);//storing user take some time
	isExceuting.OnNext(false);
	MessageBox.Show("Done");
});
```
As you can see, I have to to a lot of work, to simply do something async and prevent the user from doing this in parallel.
Now I have another problem. Some of the commands I use, have some preparation and wrap-up task that have to be done in the GUIs thread. An example: The command writes log messages that are visible in the GUI. These have to be cleared, before the new run. 
I don't wanted to expand the last result above. On the one hand, there is lots of code that can be reused in similar situation, on the other hand there is already to much fluff code. It is hard to read. I simply wanted something like this:
```csharp
StoreUserCommand = FamilyName
	.Select(s => !string.IsNullOrWhiteSpace(s) && s.Length > 5)
	.DoingAsync(() => {
		Thread.Sleep(1000);//storing a used takes a long time
		MessageBox.Show("Done");
	})
	.Prepare(() => Status.Value = "Started")//done in GUI thread
	.WrapUp(_ => Status.Value = "End") //done in GUI thread
	.ToAsyncReactiveCommand();
```

So I implemented something that used the builder pattern and some extension methods:
```csharp
public class ReactiveCommandProperties<T> {
	private readonly IObservable<bool> _can_excecute;
	private readonly Func<T> _action_to_perform_async;
	private readonly IList<Action> _preparation_actions = new List<Action>();
	private readonly IList<Action<T>> _wrapup_actions = new List<Action<T>>();
	private bool _allow_concurent_runs;

	internal ReactiveCommandProperties(IObservable<bool> can_excecute, Func<T> action_to_perform_async) {
		_can_excecute = can_excecute;
		_action_to_perform_async = action_to_perform_async;
	}

	internal ReactiveCommandProperties<T> AddPreparation(Action preparation) {
		_preparation_actions.Add(preparation);

		return this;
	}

	internal ReactiveCommandProperties<T> AddWrapUp(Action<T> wrapup) {
		_wrapup_actions.Add(wrapup);

		return this;
	}

	internal ReactiveCommand Build(out IDisposable subscription) {
		var is_executing = new ReplaySubject<bool>(1);
		is_executing.OnNext(false);
		var command = _can_excecute.CombineLatest(is_executing, (ce, ie) => ce && !ie)
			.ToReactiveCommand();

		var preparations = _preparation_actions.ToArray();
		var wrapups = _wrapup_actions.ToArray();
		var block_concurent_calls = !_allow_concurent_runs;

		subscription = command.Subscribe(async _ => {
			if (block_concurent_calls)
				is_executing.OnNext(true);
				
			foreach (var action in preparations) {
				action();
			}
				
			var task = Task.Factory.StartNew(_action_to_perform_async);
			await task;

			foreach (var wrapup in wrapups) {
				wrapup(task.Result);
			}

			if(block_concurent_calls)
				is_executing.OnNext(false);
		});

		return command;
	}

	internal ReactiveCommandProperties<T> AllowConcurentRuns() {
		_allow_concurent_runs = true;

		return this;
	}  
}

public static class ReactiveCommandExtension {
	public static ReactiveCommandProperties<T> DoingAsync<T>(this IObservable<bool> canExecute, Func<T> action_to_perform_async) {
		return new ReactiveCommandProperties<T>(canExecute, action_to_perform_async);
	}

	public static ReactiveCommandProperties<Unit> DoingAsync(this IObservable<bool> canExecute, Action action_to_perform_async) {
		return new ReactiveCommandProperties<Unit>(canExecute, ()=>
		{
			action_to_perform_async();
			return Unit.Default;
		});
	}

	public static ReactiveCommandProperties<T> AllowConcurentCalls<T>(this ReactiveCommandProperties<T> properties) {
		return properties.AllowConcurentRuns();
	} 

	public static ReactiveCommandProperties<T> Prepare<T>(this ReactiveCommandProperties<T> properties, Action prepare) {
		return properties.AddPreparation(prepare);
	}

	public static ReactiveCommandProperties<T> WrapUp<T>(this ReactiveCommandProperties<T> properties, Action<T> wrapup) {
		return properties.AddWrapUp(wrapup);
	}

	public static ReactiveCommand ToAsyncReactiveCommand<T>(this ReactiveCommandProperties<T> properties) {
		IDisposable disposable;
		return properties.Build(out disposable);
	}
	public static ReactiveCommand ToAsyncReactiveCommand<T>(this ReactiveCommandProperties<T> properties, out IDisposable subscription) {
		return properties.Build(out subscription);
	}
}
```

This solution support:
* Preventing the user from calling command multiple times by changing CanExcecute to false.
* But optional allow used to call command multiple times concurrently.
* Optionally adding Preparation tasks in GUI-thread.
* Optionally adding Wrap-up tasks in GUI-thread.
* An optional result from background task.
* Separates WHAT is done from HOW its done.
* Exposing internal created subscription to let consumer handle disposing, if he/she wish to.

The only thing that is not supported, is a custom scheduler.

**Comment by runceel** [comment]
Hi. Thank you for your feedback!!

I think that this issue solution is follows:

```cs
public class MainWindowViewModel
{
    private CountNotifier Counter { get; }
    public ReactiveProperty<string> FamilyName { get; }
    public ReactiveCommand StoreUserCommand { get; }
    public ReactiveProperty<string> Status { get; }

    public MainWindowViewModel()
    {
        this.FamilyName = new ReactiveProperty<string>();
        this.Status = new ReactiveProperty<string>();
        this.Counter = new CountNotifier();

        this.StoreUserCommand = this.FamilyName
            .MergeCountNotifierAndSelectMany(this.Counter)
            .Select(x => !string.IsNullOrWhiteSpace(x) && x.Length > 5)
            .Select(x => x && this.Counter.Count == 0)
            .ToReactiveCommand();

        this.StoreUserCommand
            .Subscribe(async _ =>
            {
                using (this.Counter.Increment())
                {
                    this.Status.Value = "Started";
                    await Task.Delay(1000);
                    this.Status.Value = "End";
                }
            });
    }

}

public static class AsyncCommandSupportExtensions
{
    public static IObservable<T> MergeCountNotifierAndSelectMany<T>(this IObservable<T> self, CountNotifier c)
    {
        return self.ToUnit().Merge(c.ToUnit()).SelectMany(self);
    }
}
```

I like this approach than your approach.
How do you think?

**Comment by BADF00D** [comment]
Hi,
thanks for quick reply. Obviously your solution is shorter and therefor more preferable. I want to give it a try, but unfortunately there is no ToUnit() extension method. I'm using 0.3.2.0 ReactiveProperty.Experimental.NET40.

But there is another problem: I think you would like to decrement the counter by using ``` using(Counter.Increment()){}```

But in my version Increment does not return a IDisposable. 

The declaration of the counter is a feature I like and dislike at the same time. On the one hand I don't want to declare a property to simply avoid concurrent calls to my command, on the other hand it allows me to control the execution of multiple (different) commands very easily.

**Comment by runceel** [comment]
Now ReactiveProperty v2.2.2 supports .NET Framework 4.0. If you try convert RP.Experimental to RP, we may help you.

RP v2.x includes some breaking changes. Especially main namespace has been changed 'CodePlex.Reactive' to 'Reactive.Bindings'.

**Comment by BADF00D** [comment]
For some reason, I accidentally used the experimental version from 2011 as I start experimenting with ReactiveProperty last week. So I simply removed all rx stuff and used the newer 2.2.2 package. 
I tested your solution and it worked. But maybe I have an better solution that don't need the extra extension method.

```csharp
StoreUserCommand = FamilyName
	.Select(x => x != null && x.Length > 5)
	.CombineLatest(
		Counter.Select(_ => Counter.Count > 0).StartWith(false), 
		(ce, ie)=> ce && !ie)
	.ToReactiveCommand();

	StoreUserCommand.Subscribe(async _ => {
		using (Counter.Increment()) {
			Status.Value = "Start";
			await Task.Delay(1000);
			Status.Value = "End";
		}
	});
```

What do you think?

**Comment by xin9le** [comment]
Very nice solution :+1: I think yours is better than ours!
In addition, thank you for using latest version.

**Comment by runceel** [comment]
Very nice!

**Comment by runceel** [comment]
I suggest a few think.
ReactiveProperty have function of validation.

follows:

```cs
// property
public ReactiveProperty<string> FamilyName { get; set; }

// constructor
FamilyName = new ReactiveProperty()
    // validation logic
    .SetValidateNotifyError(x => x != null && x.Length > 5 ? null : "ErrorMessage");

// command
StoreUserCommand = FamilyName
    .ObserveHasErrors
    .CombineLatest(Counter.Select(x => x != CountChangedStatus.Empty).StartWith(false), (x, y) => !x && !y)
    .ToReactiveCommand();
```
Thank you.

**Comment by BADF00D** [comment]
Awesome! Thanks for the hint.

I started using ReactiveProperty in productive code the last days. I realized that I can get rid of some ValueConverters I used before. I think I gonna love that framework. Thanks for the great work and quick replies. 

I read through your [examples](https://github.com/runceel/ReactiveProperty) and notices, I had to select string errors ```.Select(y => y.OfType<string>())```. So I wondert why the ```ObserveErrorChanged``` observable delivers an ```IEnumerable``` instead of ```IEnumerable<string>```. I thought all errors are strings, aren't they?

**Comment by xin9le** [comment]
Thank you for using in/on your product :+1:

Its issue is by design, because we built some validation functions on `INotifyDataErrorInfo` interface. Therefore `ObserveErrorChanged` method returns `IObservable<IEnumerable>`.

We considered string is used as error content frequently, so `SetValidateNotifyError` method provides string overload.
