### ISSUE TITLE
ObserverHasErrors in Subclasses

### ISSUE THREAD

**Issue by ElDiddi** [runceel/ReactiveProperty#51]
Hi, 

i've a problem to get the following code up and running. The CommandButton (WPF) is always disabled.
It seems, that the ViewModel class doesn't catch the ObserveHasErrors changes from Customer class.

Customer.cs
```
namespace Application1
{
	public class Customer
	{
		[Required(ErrorMessage="Customer name is requried")]
		ReactiveProperty<string> CustomerName { get; }
		
		public Customer()
		{
			this.CustomerName = new ReactiveProperty<string>("").SetValidateAttribute(() => this.CustomerName);
		}
	}
}
```

ViewModel.cs
```
namespace Application1
{
	public class MyModel
	{
		ReactiveProperty<Customer> CustomerInfo { get; } = new ReactiveProperty<Customer>(new Customer());
		
		ReactiveCommand MyCommand { get; }
		
		public MyModel()
		{
			// this doesn't work, the button is always disabled
			this.MyCommand = new ReactiveCommand(this.CustomerInfo.ObserveHasErrors);
			
			// this doesn't work too, the button is always disabled
			// this.MyCommand = new ReactiveCommand(this.CustomerInfo.Value.CustomerName.ObserveHasErrors);
			
			this.MyCommand.Subscribe(() => MyCommandImpl());
		}
		
		private void MyCommandImpl()
		{
			// Do something
		}
	}
}
```

I hope someone can help me out.

regards

**Comment by runceel** [comment]
Hi @ElDiddi .

What is CommandButton class??

I wrote sample program.(used Command property of Button class)
https://github.com/runceel/RxProp-51/tree/0e388d356f12fd08c9368cbe6addecd304f6b0ba

I have two suggestion.
1. You must implements INotifyPropertyChanged interface to ViewModel class.
https://support.microsoft.com/en-us/help/938416/a-memory-leak-may-occur-when-you-use-data-binding-in-windows-presentat

1. You miss that canExecuteSource parameter usage.
Correct code is follows:
```cs
this.MyCommand = new ReactiveCommand(this.CustomerInfo.Value.CustomerName.ObserveHasErrors.Inverse());
```
Inverse extension method is same follows:
```cs
ox.Select(x => !x)
```

And If you want multiple properties class then you can do follows approach.
https://github.com/runceel/RxProp-51/tree/bd4e9b10fd51623e79f8bafaed39a46179a443f9

Thank you.

**Comment by ElDiddi** [comment]
Thank you for the fast respone.
