### ISSUE TITLE
ReactiveProperty Android SetBinding does not support interfaces

### ISSUE THREAD

**Issue by DrifterApps** [runceel/ReactiveProperty#52]
Hi,

In an Android app, I've set all my ViewModels to use interfaces and my properties implements either IReadOnlyReactiveProperty or IReactiveProperty. But they cannot be used to call View.SetBinding().

If you want to allow my to collaborate, I can create a branch and implement it. Then I'll do a Pull Request.

Thanks

**Comment by runceel** [comment]
Thank you.

Please pull request.And could you work on vNext branch?

**Comment by DrifterApps** [comment]
Yes no problem!

**Comment by runceel** [comment]
How about this progress?
I'll close this issue one time. But you can reopen this when you have progress.
