### ISSUE TITLE
IsEnabled in ReactiveTimer

### ISSUE THREAD

**Issue by soi013** [runceel/ReactiveProperty#55]
I tried to migrate DispatcherTimer to ReactiveTimer.
But, there is not `IsEnabled` Property in ReactiveTimer.

So, can I add the Property to ReactiveTimer?
If add, which is better?

1. get only common Property 
`bool IsEnabled {get;}`

2. ReactiveProperty
`ReaciveProperty<bool> IsEnabled {get;}`

**Comment by runceel** [comment]
Thank you for your feedback!

I added the `IsEnabled` plane property to ReactiveTimer.
And I released v4.0.0-pre4 to NuGet.
https://www.nuget.org/packages/ReactiveProperty/4.0.0-pre4

Could you check this package?

**Comment by soi013** [comment]
Thank you for your quick reply and code.
It’s cool!

If I change,  add PropertyChanged to ‘Interval’  Property for consistency.

**Comment by runceel** [comment]
Hello,

I added the PropertyChanged event.

**Comment by soi013** [comment]
Thank you.
It's good!

**Comment by runceel** [comment]
I'm going to close this issue, when the v4 nuget package is released.
I'm waiting a Reactive Extensions v4 stable package.

Do you want this property in v3 package?

**Comment by soi013** [comment]
> Do you want this property in v3 package?

No. I'll wait the v4.
