### ISSUE TITLE
Github Description

### ISSUE THREAD

**Issue by soi013** [runceel/ReactiveProperty#57]
A trivial thing, Github description is empty.

I request to write this.

**ReactiveProperty_ provides MVVM and asynchronous support features under Reactive Extensions. Target framework is .NET 4.5, .NET 4.6, UWP, Xamarin.iOS, Xamarin.Android and .NET Standard 1.1.**

I can't find to do it with pull request.
how to do:
https://stackoverflow.com/questions/7757751/how-do-you-change-a-repository-description-on-github

**Comment by runceel** [comment]
Thanks!! I updated description.
