### ISSUE TITLE
ReactiveCommand Extension for constructor with Subscribe

### ISSUE THREAD

**Issue by soi013** [runceel/ReactiveProperty#58]
Hi.

I wrote these code frequently.
```
DoSomeACommand = IsBusy
    .Select(x => !x)
    .ToReactiveCommand()
    .AddTo(this.Disposable);
DoSomeACommand.Subscribe(() => model.DoSome("A"));

DoSomeBCommand = IsBusy
...
```

I suppose there are 2 problems. 
- `DoSomeACommand` was repeated.
- Constructor and Subscribe of `DoSomeACommand` were separated.

Therefore I wrote these Extension Method.
```
public static class ReactiveCommandEx
{
    public static ReactiveCommand WithSubscribe(this ReactiveCommand rcomm, Action onNext)
    {
        rcomm.Subscribe(onNext);
        return rcomm;
    }
}
```

How to use is this.
```
DoSomeACommand = IsBusy
    .Select(x => !x)
    .ToReactiveCommand()
    .WithSubscribe(() => model.DoSome("A"))
    .AddTo(this.Disposable);
```

So if I can add this method to ReactiveProperty, I will write pull-request with generic command ,test, and demo.

**Comment by amay077** [comment]
Hi,

I think ``WithSubscribe`` method no need in ReactiveProperty.
Because ``WithSubscribe`` seems like [Kotlin's ``also``](https://kotlinlang.org/api/latest/jvm/stdlib/kotlin/also.html) scope function.

``also`` is very useful in every situations and not related with Rx/ReactiveProperty.
You can just define ``Also`` and use in your app project.

```csharp
static class ObjectExtensions 
{
    // Kotlin: fun <T> T.also(block: (T) -> Unit): T
    public static T Also<T>(this T self, Action<T> block)
    {
        block(self);
        return self;
    }   
}

DoSomeACommand = IsBusy
        .Select(x => !x)
        .ToReactiveCommand()
        .Also(cmd => cmd.Subscribe(x => { /* do anything */ }))
        .AddTo(disposables);
```

**Comment by soi013** [comment]
@amay077 
`Also` method is cool!
It' useful. So I add it to my utility class.

But I still have a mind to add `WithSubscribe`. 
Because, `WithSubscribe` is shorter and lower layer than `Also`.

**Comment by runceel** [comment]
@amay077 
Thanks! The Kotlin is a very cool language. I like it too.

@soi013 
Hi,
This extension method has a problem.
How do we unsubscribe?
I prefer the `Also` extension method.

```cs
var disposables = new CompositeDisposable();
var fooDisposables = new CompositeDisposable();
var barDisposables = new CompositeDisposable();
DoSomeACommand = IsBusy
    .Select(x => !x)
    .ToReactiveCommand()
    .Also(cmd => cmd.Subscribe(x => { /* action1 */}).AddTo(fooDisposables))
    .Also(cmd => cmd.Subscribe(x => { /* action2 */ }).AddTo(barDisposables))
    .AddTo(disposables);

// unsubscribe action1
fooDisposables.Dispose();

// unsbscribe action2
barDisposables.Dispose();

// unsbscribe all
disposables.Dispose();
```

**Comment by runceel** [comment]
@soi013 
But, I agree that the current code is not cool.
I want to add some feature.

**Comment by soi013** [comment]
@runceel 
Hi. Thank you your comment.
Yes this is problem.
I have basic question.
If ReactiveCommand is disposed, Subscribe is disposed too and memory leak dosen't happen, Right?

**Comment by soi013** [comment]
@runceel
Hi. Thank you your comment.
Yes this is problem.
I have basic question.
If ReactiveCommand is disposed, Subscribe is disposed also and memory leak dosen't happen, Right?

**Comment by runceel** [comment]
@soi013 
My understanding is that it doesn't happen leak.

**Comment by runceel** [comment]
@soi013 
I published a new release.
Add WithSubscribe extension methods to ReactiveCommand class and AsyncReactiveCommand class.

https://github.com/runceel/ReactiveProperty/releases/tag/v4.0.0-pre5

Usage
```cs
var disposable = new CompositeDisposable();
IObservable<bool> canExecuteSource = ...;
var cmd = canExecuteSource
    .ToReactiveCommand()
    .WithSubscribe(() => { ... })
    .AddTo(disposable);
```

If you want to unsbscribe per subscription, then following override methods:
```cs
IDIsposable d1 = null;
IDisposable d2 = null;

IObservable<bool> canExecuteSource = ...;
var cmd = canExecuteSource
    .ToReactiveCommand()
    .WithSubscribe(() => { ... }, x => d1 = x)
    .WithSubscribe(() => { ... }, x => d2 = x)
    .AddTo(disposable);

// unsbscribe per subscription..
d1.Dispose();
d2.Dispose();
```

**Comment by soi013** [comment]
@runceel 
Thunk you for accepting my suggest.
It's good.

**Comment by runceel** [comment]
I released a new package.
This release includes this feature.
