### ISSUE TITLE
Signed library needed

### ISSUE THREAD

**Issue by Garfield550** [runceel/ReactiveProperty#59]
References:
[Microsoft Docs: Strong-Named Assemblies][0]
[Stackoverflow: Why use strong named assemblies?][1]

[0]: https://docs.microsoft.com/en-us/dotnet/framework/app-domains/strong-named-assemblies
[1]: https://stackoverflow.com/questions/2354129/why-use-strong-named-assemblies

**Comment by runceel** [comment]
Could you tell me when did you need the signed library?
And sorry, I don't know about certificate well. Please tell me that which certificate should I use? In this case, is a self-signed OK?

**Comment by Garfield550** [comment]
Q: Please tell me that which certificate should I use? In this case, is a self-signed OK?

A: Strong Name Key not Code Signing Certificates.

Use Strong Name Key(\*.snk) not Personal Information Exchange(\*.pfx)

1. In **Solution Explorer**, open **Properties**.
1. Choose **Signing** tab.
1. Select **Sign the assembly** box.
1. In **Choose a strong name key** file box, choose **<New…>** and enter the *filename* in the **Create Strong Name Key** dialog box.
1. **Important**: Uncheck **Protect my key file with a password** and click **OK**.

参照:
[厳密な名前付きアセンブリ][1]
[方法 : 厳密な名前でアセンブリに署名する][2]

[1]: https://docs.microsoft.com/ja-jp/dotnet/framework/app-domains/strong-named-assemblies
[2]: https://docs.microsoft.com/ja-jp/dotnet/framework/app-domains/how-to-sign-an-assembly-with-a-strong-name

**Comment by runceel** [comment]
@Garfield550 
Thank you.

I signed assemblies. And released a package to NuGet.

The version is v4.0.1-pre1.
Could you check it?

https://www.nuget.org/packages/ReactiveProperty/4.0.1-pre1

**Comment by Garfield550** [comment]
@runceel 
Awesome, thank a lot.

**Comment by runceel** [comment]
I'll release it after few days.
