### ISSUE TITLE
Easier way to get on IObservable<int> from CountNotifier

### ISSUE THREAD

**Issue by BADF00D** [runceel/ReactiveProperty#6]
Hallo,
I'm using the CountNotifier in order count calls to a command as you suggest in my last issue #5.
For this purpose, I need to actual value stored in CountNotifier which I select in this way:
```
_callToCommandCounter = new CountNotifier();
_callToCommandCounter .Select(_ => _callToCommandCounter .Count > 0)
``` 
This works, but I prefer to have a possibility to observe the value directly. Something like this:
```
_callToCommandCounter.ObserveCount(count => count > 0);
```

What do you think?

**Comment by runceel** [comment]
Thank you for your feedback!

I think ObserveProperty extension method is useful.

fllows:

```cs
// using Reactive.Bindings.Extensions;
// using Reactive.Bindings.Notifiers;

var c = new CountNotifier();
c.ObserveProperty(x => x.Count)
    .Subscribe(x => Console.WriteLine(x));

c.Increment();
c.Decrement();

// Output 0 -> 1 -> 0
```
How do you think?

**Comment by BADF00D** [comment]
Works great, thanks!
