### ISSUE TITLE
.NET Core

### ISSUE THREAD

**Issue by janus007** [runceel/ReactiveProperty#60]
Hello

Do you have any plans about .Net Core 2.0 ?

**Comment by runceel** [comment]
@janus007 
This library's target platform is .NET Standard 1.3.
Already can use on the .Net Core 2.0.

I tryed following steps.

- Created .NET Core Console app
- Added ReactiveProperty reference 
- Wrote below code:

```cs
using Reactive.Bindings;
using System;

namespace ConsoleApp3
{
    class Program
    {
        static void Main(string[] args)
        {
            var rp = new ReactiveProperty<string>("initial value");
            rp.Subscribe(x => Console.WriteLine(x));

            rp.Value = ".NET Core";
            rp.Value = "ReactiveProperty";
        }
    }
}
```

- Launch the program

Output is as below:

```
initial value
.NET Core
ReactiveProperty
```

Do you have some issues about this library on the .NET Core 2.0 platform?
If you have issues, then let me know.

**Comment by janus007** [comment]
Thank you, I tried as per your recommendation but ReactiveProperty couldn't be found which is kind of strange. 
I solved it by recompiling source to .Net Core 2.0 and that succeeded without any issues.

Excellent framework, I've previously used it for Unity game development, this time I'm using it for a native .Net application:)

**Comment by runceel** [comment]
Hi @janus007,
How about this issue?
I'm waiting your reply. I hope that you can use this library in your product.

Thank you!

**Comment by runceel** [comment]
Hi @janus007,
I'll close this issue.
If changing status about this, then please re-open.

Thank you!
