### ISSUE TITLE
Add IGrouping implementation

### ISSUE THREAD

**Issue by worldbeater** [runceel/ReactiveProperty#62]
Hello @runceel! Thanks for your great library.

Here is a short feature-request! While developing modern applications, both desktop and mobile ones, developers sometimes need to group elements in ListViews somehow and show group titles. Most XAML-based platforms are designed to provide support for grouping elements by using IGrouping<TKey, TValue> interface, so, often developers need to write their own implementations to let the UI know if a user has modified certain group of elements. The most commonly used implementation is the following:
```csharp
public class ObservableGrouping<TKey, TValue> : ObservableCollection<TValue>, IGrouping<TKey, TValue>
{
    public ObservableGrouping(IGrouping<TKey, TValue> group) : base(grouping) => Key = group.Key;

    public ObservableGrouping(TKey key, IEnumerable<TValue> elements) : base(elements) => Key = key;

    public TKey Key { get; }
}
```
So, I think adding reactive IGrouping<,> implementation to the library could potentially make our lifes easier! I've created one, so please take a look, it's just a derived class from ReactiveCollection<T>! 
```csharp
public class ReactiveGrouping<TKey, TValue> : ReactiveCollection<TValue>, IGrouping<TKey, TValue>
{
    public ReactiveGrouping(TKey key) => Key = key;

    public ReactiveGrouping(TKey key, IScheduler scheduler) : base(scheduler) => Key = key;

    public ReactiveGrouping(TKey key, IObservable<TValue> source) : base(source) => Key = key;

    public ReactiveGrouping(TKey key, IObservable<TValue> source, IScheduler scheduler) : base(source, scheduler) => Key = key;

    public ReactiveGrouping(IGrouping<TKey, TValue> group) : base(group.ToObservable()) => Key = group.Key;

    public TKey Key { get; }
}
```
Key is an immutable value during whole object lifetime here. Been thinking on making it an Observable<> too, but haven't really come across any cases where mutation of group titles in ListViews was desirable.

Thanks.

**Comment by runceel** [comment]
@worldbeater 
Thank you for requesting a feature.

It sounds good. But, you can already use the feature with [DynamicData](https://github.com/RolandPheasant/DynamicData).

Do you know this?
I think that this can use together with ReactiveProperty. If you have issues when using a couple libraries, then.let me know.

**Comment by worldbeater** [comment]
Thanks for suggesting such a great library! Really powerful. And for more complicated scenarios than just displaying a data set, a new ViewModel can easily be created. So, maybe groupings are not in responsibility scope of ReactiveProperty :)

**Comment by runceel** [comment]
It's my pleasure.
Thank you!
