### ISSUE TITLE
Making simpliest initialization less verbose

### ISSUE THREAD

**Issue by worldbeater** [runceel/ReactiveProperty#64]
There may be some cases when properties should be initialized from a simple default value. False for IsLoading property, true for IsEmpty property and so on. To initialize my indicator properties I currently have to use this:
```csharp
Query = new ReactiveProperty<string>(string.Empty);
IsGreeting = new ReactiveProperty<bool>(true);
IsLoading = new ReactiveProperty<bool>(false);
IsEmpty = new ReactiveProperty<bool>(false);
```
This is very nice, but seems to be quite verbose! :)

To simplify initialization **static implicit operator** magic can be used. For example, this code:
```csharp
public class ReactiveProperty<TValue> 
{
    public static implicit operator ReactiveProperty<TValue>(TValue value) 
    {
        return new ReactiveProperty<TValue>(value);
    }
}
```
Will allow us to shorten our initializers directly to this:
```csharp
Query = string.Empty;
IsGreeting = true;
IsLoading = false;
IsEmpty = false;
```
Or this (if we use ValueTuples and don't like many lines of code)
```csharp
Query = string.Empty;
(IsGreeting, IsLoading, IsEmpty) = (true, false, false);
```
Nice!

**Comment by soi013** [comment]
@worldbeater 
I think shorter code is better code, but the **implicit operator** is confusing.

Commonest case is mixing these code up.
`Query = string.Empty;`
`Query.Value = string.Empty;`

`Value` is same, but reference is not same.

**Comment by worldbeater** [comment]
> implicit operator is confusing
I'm afraid you are right, implicit operators can potentially lead to misunderstanding on how does this code work. But IMHO this issue can be resolved by providing detailed documentation and examples on how to correctly declare and mutate reactive properties!

Anyway, my opinion is that reducing the amount of boilerplate code in most cases is a right choice. I prefer declaring initial property values explicitly right before subscribing to any events or implementing logic, but writing long type names **twice** (declaration and definition) is such a pain.

**Comment by runceel** [comment]
@worldbeater 
Thank you for your feedback. I thought that tried implement this feature previously.

But, I didn't implement this feature. Because this is confusing and easy to mistake.(same as @soi013's comment.)

For example:

```cs
public class Sample
{
    public ReactiveProperty<string> Name { get; set; }

    public Sample()
    {
        Name = "init value"; // Correct
    }
    
    public void UpdateNameValue()
    {
        // It is a bug! And no compile error.
        Name = "new value";
        // Correctly code is as below
        Name.Value = "new value";
    }
}
```

I like a short code too. But, I don't like implicit operator because previous reason.
