### ISSUE TITLE
ReactivePropertySlim throws NotSupportedException when used in binding.

### ISSUE THREAD

**Issue by Tan90909090** [runceel/ReactiveProperty#67]
I'm developing a WPF application.
I tried using ReactivePropertySlim, and I noticed that it throw NotSupportedException when used in a binding.
An Exception is thrown at ``Reactive.Bindings.ReactivePropertySlim`1.System.ComponentModel.INotifyDataErrorInfo.add_ErrorsChanged(EventHandler`1 value)``.
For example, this occurs with the following code:
```csharp
using System.Windows;
using Reactive.Bindings;

namespace WpfTest
{
    public partial class MainWindow : Window
    {
        public MainWindow()
        {
            InitializeComponent();
            this.DataContext = new ViewModel();
        }
    }

    public class ViewModel
    {
        public ReactivePropertySlim<string> Slim { get; } = new ReactivePropertySlim<string>("test");
    }
}
```
```xml
<Window x:Class="WpfTest.MainWindow"
        xmlns="http://schemas.microsoft.com/winfx/2006/xaml/presentation"
        xmlns:x="http://schemas.microsoft.com/winfx/2006/xaml">
    <TextBlock Text="{Binding Slim.Value}" />
</Window>
```

I found that I can avoid this issue by setting Binding.ValidatesOnNotifyDataErrors to false:
```xml
<Window x:Class="WpfTest.MainWindow"
        xmlns="http://schemas.microsoft.com/winfx/2006/xaml/presentation"
        xmlns:x="http://schemas.microsoft.com/winfx/2006/xaml">
    <TextBlock Text="{Binding Slim.Value, ValidatesOnNotifyDataErrors=False}" />
</Window>
```
However it is verbose to set ValidatesOnNotifyDataErrors at every bindings.
It would be nice if you could change this behavior.

**Comment by neuecc** [comment]
Thank you.
I've changed to empty event handling(do nothing on add/remove) instead of throws NotSuportedException.

**Comment by runceel** [comment]
Thank you.
I've merged the PR and published a new package to NuGet.

**Comment by Tan90909090** [comment]
I tried a new package and confirmed that a binding succeeded.
Thank you!
