### ISSUE TITLE
Update issues: Already defined assemblies

### ISSUE THREAD

**Issue by gabrielrobert** [runceel/ReactiveProperty#70]
I just updated my projects to `ReactiveProperty 4.1.1`. However, I get some errors inside my test projects:

`The type 'LocalScheduler' is defined in an assembly that is not referenced. You must add a reference to assembly 'System.Reactive.Core, Version=3.0.3000.0, Culture=neutral, PublicKeyToken=94bc3704cddfc263'.
`

` The type 'IScheduler' is defined in an assembly that is not referenced. You must add a reference to assembly 'System.Reactive.Interfaces, Version=3.0.0.0, Culture=neutral, PublicKeyToken=94bc3704cddfc263'.`

I tried to add those packages, but now the errors are:

` The type 'IScheduler' exists in both 'System.Reactive.Interfaces, Version=3.0.0.0, Culture=neutral, PublicKeyToken=94bc3704cddfc263' and 'System.Reactive, Version=4.0.0.0, Culture=neutral, PublicKeyToken=94bc3704cddfc263'`

`The type 'ImmediateScheduler' exists in both 'System.Reactive.Core, Version=3.0.3000.0, Culture=neutral, PublicKeyToken=94bc3704cddfc263' and 'System.Reactive, Version=4.0.0.0, Culture=neutral, PublicKeyToken=94bc3704cddfc263'`

I tried to:
1. Close Visual Studio
2. Delete `packages` folder
3. Delete all `bin/obj` folders

Any ideas on what could be my issue?

**Comment by runceel** [comment]
Thanks for your feedback.

Does this issue relate the below issue?
https://github.com/Reactive-Extensions/Rx.NET/issues/299

I would like to fix your issue,
Could you give me the re-present minimam project?
