### ISSUE TITLE
Intellisense can't find ReactiveProperty Type

### ISSUE THREAD

**Issue by Vedaevolution** [runceel/ReactiveProperty#75]
Dear Community,

the following problem appeared to me:

![Error Image](https://s2.imagebanana.com/file/180307/3kghsCZv.png)

I'm using Resharper and it seems it is not able to tell the generic type of the reactive property. Compiling this code works of course. If i look at the issue it's not showing "string" for the Value property but "???".
Can something be done about this. Of course it is not crititcal because the code can be compiled. 

Nevertheless it's still not nice having errors popping up in the IDE.

Thank you very much

**Comment by Garfield550** [comment]
I think you can try to uninstall ReSharper.

**Comment by Vedaevolution** [comment]
That is obviously a solution. ReSharper is nice tool to use. The mere fact that this only occurs with his library indicates that something with the library code is not optimal.

**Comment by runceel** [comment]
Thank you for your feedback.
But I don't use ReSharper. 

I think that this issue is ReSharper's issue.
How do you think?

If you find the problem in ReactiveProperty, then let me know.
