### ISSUE TITLE
Update issues: System.Reactive v4.0.0

### ISSUE THREAD

**Issue by soi013** [runceel/ReactiveProperty#79]
ReactiveProperty 4.2.2 conflicts System.Reactive v4.0.0.

Because System.Reactive v4.0.0. dosen't contains System.Reactive.Core.

So, I think there are 2 solutions.

- Add System.Reactive.Compatibility
- Update for System.Reactive v4 (BUT .NET Starndard 2+ support)

**Comment by runceel** [comment]
So, as you say, my understanding is that when using ReactiveProperty v4.2.2 with System.Reactive v4.0.0, should add System.Reactive.Compatibility manually.

I released ReactiveProperty v5.0.0 which depends on System.Reactive v4.0.0.

**Comment by soi013** [comment]
Thank you. It's GOOD!
