### ISSUE TITLE
DynamicData. ObserveAddChanged 

### ISSUE THREAD

**Issue by Ossiostborn** [runceel/ReactiveProperty#84]
I did:

```
ReadOnlyObservableCollection<ICommandCollection> workView;

workViewmodel
	.Connect()
	.ObserveOnUIDispatcher()        
	.Bind(out workView)
	.DisposeMany()
	.Subscribe()
	.AddTo(dissen);

workview
	.ObserveAddChanges()
	.Subscribe(_=> do something);

workViewmodel.AddOrUpdate(newItem); // <- AddObserver is not reacting
```

First time adding an workViewmodel  AddObserver will not publish this added ICommandCollection. ObserveCollectionChanges Shows: the changeStatus is Reset, sender contains this added Item. Should this AddObserver here be active?

**Comment by runceel** [comment]
Sorry for my late reply.
Because I don't know the Bind method, I couldn't understand your issue.

Could you provide me completed code for reproduction.

**Comment by Ossiostborn** [comment]
No problem. I did not look daily too. 

Here is the clean excample. The problem isn't that ReadOnlyObservableCollection hasn't an empty constructor. I did try the same with an defined Datatype. First Add  is not observable with ObserveAddChanges. 

```
var workViewmodel= new SourceList<string>();
ReadOnlyObservableCollection<string> workView;

workViewmodel
	.Connect()
	.ObserveOnUIDispatcher()        
	.Bind(out workView)
	.Subscribe();

workview
	.ObserveAddChanges()
	.Subscribe(_=> do something);

workViewmodel.Add("newItem"); // <- AddObserver is not reacting
```

**Comment by runceel** [comment]
I traced the events using below code:

```cs
using DynamicData;
using Reactive.Bindings.Extensions;
using System;
using System.Collections.ObjectModel;
using System.Collections.Specialized;
using System.Diagnostics;
using System.Windows;

namespace WpfApp1
{
    public partial class MainWindow : Window
    {
        public SourceList<string> WorkViewModel { get; }
        private ReadOnlyObservableCollection<string> _workView;
        public ReadOnlyObservableCollection<string> WorkView => _workView;
        public MainWindow()
        {
            WorkViewModel = new SourceList<string>();
            WorkViewModel
                .Connect()
                .ObserveOnUIDispatcher()
                .Bind(out _workView)
                .Subscribe();

            WorkView
                .ObserveAddChanged()
                .Subscribe(_ => Debug.WriteLine("Added!!"));
            ((INotifyCollectionChanged)WorkView).CollectionChanged += (_, e) => Debug.WriteLine(e.Action);

            InitializeComponent();
        }

        private void Button_Click(object sender, RoutedEventArgs e)
        {
            WorkViewModel.Add("newItem");
        }
    }
}
```

When the first call the `Add` method of the `SourceList<string>` class, `Reset` is displayed on the debug console.
I don't enough know inside of DynamicData. However, I guess that you should subscribe `CollectionChanged` event.
`ObserveAddChanged` method is only passing `Add` action. In this case, I guess that `ObserveCollectionChanged` method is better. This is same as subscribe CollectionChanged event directly.

**Comment by runceel** [comment]
I closed the issue.
If you have some updates for this issue, then feel free re-open this. 😊
