### ISSUE TITLE
Can not resolve reference: `System.Threading.Tasks.Extensions`

### ISSUE THREAD

**Issue by runceel** [runceel/ReactiveProperty#87]
This issue is related: https://github.com/dotnet/reactive/issues/803

**Comment by ChrisPulman** [comment]
The root cause is in package System.Threading.Tasks.Extensions there are no dll's in the targets other than NetStandard2.0

A temporary resolution could be to add the following to your project file manually

```
<ItemGroup>
    <PackageReference Include="System.Runtime.CompilerServices.Unsafe" Version="4.5.2"/>
  </ItemGroup>
  <ItemGroup>
    <Reference Include="System.Threading.Tasks.Extensions">
      <HintPath>$(UserProfile)\.nuget\packages\system.threading.tasks.extensions\4.5.1\lib\netstandard2.0\System.Threading.Tasks.Extensions.dll</HintPath>
    </Reference>
  </ItemGroup>
```

**Comment by runceel** [comment]
It was fixed on latest Xamarin.Android.
I've checked the issue is not occurred on Visual Studio 2019.
