### ISSUE TITLE
EventToReactiveProeprty from Assembly "ReactiveProperty.NET45" is built with an older version of Blend SDK

### ISSUE THREAD

**Issue by TaviTruman** [runceel/ReactiveProperty#9]
This code results in an error when I'm using Blend 2015 and that's too bad because you can't use Blend to design WPF UI if you're using ReactiveProperty!

Here's the error message: 
Type type 'EventToReactive' from assembly 'ReactiveProeprty.NET45' is built with older version of the Blend SDK, and is not supported in a Windows Presentation Framework 4 project.

<coreInteractivity:Interaction.Triggers>

            <coreInteractivity:EventTrigger 
                    x:Name="DataCardIsLoaded"
                    EventName="Loaded" 
                    SourceName="UIProgramInfoData">

                <reactiveProperty:EventToReactiveProperty
                        x:Name="ReactOnLoaded" 
                        ReactiveProperty="{Binding ReactOnLoaded, UpdateSourceTrigger=PropertyChanged}" />

            </coreInteractivity:EventTrigger>

            <coreInteractivity:EventTrigger 
                    x:Name="FieldLayoutReactor"
                    EventName="FieldLayoutInitialized"
                    SourceName="UIProgramInfoData">

                <reactiveProperty:EventToReactiveProperty 
                        x:Name="ReactOnInitialized"
                        IgnoreEventArgs="False"
                        ReactiveProperty="{Binding ReactOnInitialized, UpdateSourceTrigger=PropertyChanged}" />

            </coreInteractivity:EventTrigger>

        </coreInteractivity:Interaction.Triggers>

**Comment by runceel** [comment]
Thank you for your feedback.

We have changed "project reference" and re-packaging the ReactiveProperty v2.2.5. Please confirm.
(However we cloudn't reproduce your issue in our environment...)

**Comment by TaviTruman** [comment]
Thank you the problem seems to have been resolved.

Tavi

**Comment by TaviTruman** [comment]
Guys this problem has returned in the latest build.
